-- ==========================================
-- FASE 1: LIMPIEZA DE TABLAS (CASCADE)
-- ==========================================
DROP TABLE IF EXISTS HISTORIAL_ESTADO CASCADE;
DROP TABLE IF EXISTS NOTIFICACION CASCADE;
DROP TABLE IF EXISTS COMENTARIO CASCADE;
DROP TABLE IF EXISTS UTILIZA CASCADE;
DROP TABLE IF EXISTS REGISTRO_AVANCE CASCADE;
DROP TABLE IF EXISTS DEPENDE CASCADE;
DROP TABLE IF EXISTS ES_MIEMBRO CASCADE;
DROP TABLE IF EXISTS TAREA CASCADE;
DROP TABLE IF EXISTS PROYECTO CASCADE;
DROP TABLE IF EXISTS RECURSO_MATERIAL CASCADE;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;

-- ==========================================
-- FASE 2: CREACIÓN DE TABLAS MAESTRAS
-- ==========================================
CREATE TABLE USUARIO (
    id_usuario       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci               VARCHAR(20)  UNIQUE NOT NULL,
    nombre           VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100),
    fecha_nacimiento DATE,
    sexo             CHAR(1) CHECK (sexo IN ('M','F')),
    telefono         VARCHAR(50),
    direccion        TEXT,
    correo           VARCHAR(100) UNIQUE NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    rol              VARCHAR(50)  NOT NULL,
    especialidad     VARCHAR(100),
    costo_por_hora   DECIMAL(10,2) DEFAULT 0.00,
    foto_perfil      TEXT,
    fecha_registro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo           BOOLEAN DEFAULT TRUE
);

CREATE TABLE CLIENTE (
    id_cliente         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa     VARCHAR(150) NOT NULL,
    nit                VARCHAR(50)  UNIQUE NOT NULL,
    telefono_contacto  VARCHAR(50),
    correo_empresa     VARCHAR(100),
    direccion_empresa  TEXT,
    fecha_registro     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    activo             BOOLEAN DEFAULT TRUE
);

CREATE TABLE RECURSO_MATERIAL (
    id_recurso     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_recurso VARCHAR(150) NOT NULL,
    descripcion    TEXT,
    unidad_medida  VARCHAR(50),
    costo_unitario DECIMAL(12,2) NOT NULL,
    categoria      VARCHAR(100)
);

-- ==========================================
-- FASE 3: TABLAS TRANSACCIONALES
-- ==========================================
CREATE TABLE PROYECTO (
    id_proyecto        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_proyecto    VARCHAR(200) NOT NULL,
    descripcion        TEXT,
    fecha_inicio       DATE NOT NULL,
    fecha_fin_estimada DATE,
    fecha_fin_real     DATE,
    presupuesto_total  DECIMAL(12,2) NOT NULL,
    estado             VARCHAR(50) DEFAULT 'Pendiente'
                       CHECK (estado IN ('Pendiente','En Progreso','Finalizada','Cancelado')),
    fecha_creacion     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_cliente         INTEGER REFERENCES CLIENTE(id_cliente)  ON DELETE RESTRICT,
    id_gerente         INTEGER REFERENCES USUARIO(id_usuario)  ON DELETE SET NULL
);

CREATE TABLE TAREA (
    id_tarea           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR(200) NOT NULL,
    descripcion        TEXT,
    fecha_inicio       DATE NOT NULL,
    fecha_fin_estimada DATE,
    fecha_fin_real     DATE,
    horas_estimadas    INTEGER NOT NULL CHECK (horas_estimadas > 0),
    prioridad          VARCHAR(50) DEFAULT 'Media'
                       CHECK (prioridad IN ('Baja','Media','Alta')),
    estado             VARCHAR(50) DEFAULT 'Pendiente'
                       CHECK (estado IN ('Pendiente','En Progreso','Finalizada','Cancelada')),
    id_proyecto        INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE,
    id_usuario         INTEGER REFERENCES USUARIO(id_usuario)   ON DELETE SET NULL
);

-- ==========================================
-- FASE 4: TABLAS INTERMEDIAS Y DETALLE
-- ==========================================
CREATE TABLE ES_MIEMBRO (
    id_proyecto     INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE,
    id_usuario      INTEGER REFERENCES USUARIO(id_usuario)   ON DELETE CASCADE,
    rol_en_proyecto VARCHAR(100),
    fecha_ingreso   DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (id_proyecto, id_usuario)
);

CREATE TABLE DEPENDE (
    id_tarea        INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
    id_tarea_previa INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
    PRIMARY KEY (id_tarea, id_tarea_previa),
    CHECK (id_tarea <> id_tarea_previa)
);

CREATE TABLE REGISTRO_AVANCE (
    id_registro       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_reporte     DATE DEFAULT CURRENT_DATE,
    horas_trabajadas  NUMERIC(5,2) NOT NULL CHECK (horas_trabajadas > 0),
    porcentaje_avance INTEGER CHECK (porcentaje_avance BETWEEN 0 AND 100),
    detalle_trabajo   TEXT,
    estado            VARCHAR(20) DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Aprobado', 'Rechazado')),
    id_tarea          INTEGER REFERENCES TAREA(id_tarea)     ON DELETE CASCADE,
    id_usuario        INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
);

CREATE TABLE UTILIZA (
    id_proyecto    INTEGER REFERENCES PROYECTO(id_proyecto)        ON DELETE CASCADE,
    id_recurso     INTEGER REFERENCES RECURSO_MATERIAL(id_recurso) ON DELETE CASCADE,
    cantidad_usada INTEGER NOT NULL CHECK (cantidad_usada > 0),
    fecha_uso      DATE DEFAULT CURRENT_DATE,
    observacion    TEXT,
    PRIMARY KEY (id_proyecto, id_recurso)
);

CREATE TABLE COMENTARIO (
    id_comentario    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenido        TEXT NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_tarea         INTEGER REFERENCES TAREA(id_tarea)     ON DELETE CASCADE,
    id_usuario       INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
);

CREATE TABLE NOTIFICACION (
    id_notificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_alerta      VARCHAR(50) NOT NULL
                     CHECK (tipo_alerta IN ('RETRASO_TAREA','LIMITE_PRESUPUESTO','ASIGNACION','SISTEMA')),
    titulo           VARCHAR(150) NOT NULL,
    mensaje          TEXT NOT NULL,
    fecha_generacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    leido            BOOLEAN DEFAULT FALSE,
    id_usuario       INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
    id_referencia    INTEGER,
    nivel_prioridad  VARCHAR(20) DEFAULT 'Normal'
                     CHECK (nivel_prioridad IN ('Normal','Advertencia','Critica'))
);

CREATE TABLE HISTORIAL_ESTADO (
    id_historial     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_referencia VARCHAR(50) NOT NULL,
    id_referencia    INTEGER NOT NULL,
    estado_anterior  VARCHAR(50),
    estado_nuevo     VARCHAR(50) NOT NULL,
    fecha_cambio     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario       INTEGER REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);

-- ==========================================
-- FASE 5: INSERCIÓN DE DATOS INTACTOS (USUARIOS, CLIENTES, PROYECTOS)
-- ==========================================
INSERT INTO USUARIO (id_usuario, ci, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, sexo, telefono, direccion, correo, password_hash, rol, especialidad, costo_por_hora) VALUES
(1001,'8345612','Roberto',     'Alarcón',   'Méndez', '1985-04-12','M','71234567','Av. Arce #123, Edificio Empresarial', 'r.alarcon@apexdev.bo',     'pass_seguro_1','Admin',   'Infraestructura TI',          0.00),
(1002,'9123845','Valeria',     'Cárdenas',  'Ríos',   '1990-08-25','F','79823411','Calle 21 de Calacoto #45',            'v.cardenas@apexdev.bo',    'pass_seguro_2','Admin',   'Seguridad y Accesos',         0.00),
(1003,'6452391','Marcelo',     'Quiroga',   'Paz',    '1982-11-03','M','61239844','Av. Bush #902',                       'm.quiroga@apexdev.bo',     'pass_seguro_3','Admin',   'Auditoría de Sistemas',       0.00),
(1004,'7531982','Andrea',      'Soliz',     'Vaca',   '1988-01-15','F','77521099','Av. 6 de Agosto #1020',               'a.soliz@apexdev.bo',       'gerente_123',  'Gerente', 'Gestión Ágil (Scrum)',       180.00),
(1005,'8642109','Diego',       'Torrez',    'Salinas','1986-07-22','M','76451233','Zona Sur, Obrajes Calle 10',          'd.torrez@apexdev.bo',      'gerente_123',  'Gerente', 'Proyectos Cloud',            190.50),
(1006,'5321487','Camila',      'Vargas',    'López',  '1992-05-10','F','71548766','Sopocachi, Calle Ecuador #33',        'c.vargas@apexdev.bo',      'gerente_123',  'Gerente', 'Desarrollo Móvil',           175.00),
(1007,'8523697','Miguel Ángel','Castro',    'Silva',  '1995-06-12','M','77711223','Alto Obrajes Sector A',               'm.castro@apexdev.bo',      'emp_pass_1',   'Empleado','Backend Node.js',             90.00),
(1008,'7412589','Sofía',       'Ramírez',   'Luna',   '1997-10-04','F','65432109','Irpavi II, Calle 4',                  's.ramirez@apexdev.bo',     'emp_pass_2',   'Empleado','Frontend React',              85.00),
(1009,'9632587','Carlos',      'Llanos',    'Pérez',  '1990-01-20','M','78965412','Achumani, Calle 22',                  'c.llanos@apexdev.bo',      'emp_pass_3',   'Empleado','DBA PostgreSQL',             110.00),
(1010,'1239874','Elena',       'Poma',      'Quispe', '1994-08-15','F','71122334','Av. Buenos Aires #1500',              'e.poma@apexdev.bo',        'emp_pass_4',   'Empleado','QA Automation',               80.00),
(1011,'4561237','Julio César', 'Ruiz',      'García', '1992-11-25','M','62233445','Cota Cota, Calle 30',                 'j.ruiz@apexdev.bo',        'emp_pass_5',   'Empleado','DevOps Docker/AWS',          120.00),
(1012,'7894561','Daniela',     'Arce',      'Mora',   '1996-03-08','F','73344556','San Miguel, Bloque B',                'd.arce@apexdev.bo',        'emp_pass_6',   'Empleado','UI/UX Designer Figma',        75.00),
(1013,'3217896','Luis Fernando','Choque',   'Mamani', '1993-07-14','M','74455667','Villa Fátima, Plaza Principal',       'l.choque@apexdev.bo',      'emp_pass_7',   'Empleado','Backend Java Spring',         95.00),
(1014,'6541239','Gabriela',    'Montenegro','Díaz',   '1998-09-02','F','65566778','Sopocachi, Calle Rosendo',            'g.montenegro@apexdev.bo',  'emp_pass_8',   'Empleado','Frontend Angular',            85.00),
(1015,'9873214','Héctor',      'Salinas',   'Vega',   '1991-04-19','M','76677889','Miraflores, Calle Díaz',              'h.salinas@apexdev.bo',     'emp_pass_9',   'Empleado','Desarrollo Android Kotlin',  100.00),
(1016,'1472583','Mariana',     'Cortez',    'Rivas',  '1995-12-11','F','77788990','Av. 16 de Julio (Prado)',             'm.cortez@apexdev.bo',      'emp_pass_10',  'Empleado','Desarrollo iOS Swift',       105.00),
(1017,'9637418','Ricardo',     'Medina',    'Soto',   '1991-06-25','M','65455667','El Alto, Cruce Viacha',               'r.medina@apexdev.bo',      'emp_pass_11',  'Empleado','Ingeniero de Datos',         105.00),
(1018,'4562589','Tomás',       'Aguilar',   'Sosa',   '1989-12-25','M','71033445','Av. Potosí #200',                     't.aguilar@apexdev.bo',     'emp_pass_12',  'Empleado','Consultor SAP',              140.00),
(1019,'1479512','Fabiola',     'Sánchez',   'Díaz',   '1997-04-16','F','66588990','El Alto, 16 de Julio',                'f.sanchez@apexdev.bo',     'emp_pass_13',  'Empleado','Redes y Telecomunicaciones',  90.00);

INSERT INTO CLIENTE (id_cliente, nombre_empresa, nit, telefono_contacto, correo_empresa, direccion_empresa) VALUES
(1001,'Banco Nacional de Bolivia (BNB)',     '1011223340','2123344', 'info@bnb.com.bo',          'Av. Camacho Esq. Colón, La Paz'),
(1002,'Banco de Crédito de Bolivia (BCP)',   '1055667780','2156677', 'contacto@bcp.com.bo',      'Av. Hernando Siles, Obrajes'),
(1003,'La Boliviana Ciacruz Seguros',        '1066778890','2167788', 'atencion@lbc.com.bo',      'Av. 20 de Octubre, La Paz'),
(1004,'Jalasoft Corporación',                '1133445560','77712345','contact@jalasoft.com',      'Parque Tecnológico, Cochabamba'),
(1005,'PedidosYa Bolivia S.A.',              '1455667780','77799888','contacto@pedidosya.com.bo', 'Av. San Martín, Santa Cruz'),
(1006,'Universidad Católica Boliviana (UCB)','1399001120','2490011', 'contacto@ucb.edu.bo',      'Av. 14 de Septiembre, La Paz');

INSERT INTO RECURSO_MATERIAL (id_recurso, nombre_recurso, descripcion, unidad_medida, costo_unitario, categoria) VALUES
(1001,'Laptop Dell Latitude Core i7 16GB RAM', 'Equipo de alto rendimiento para desarrollo',       'Unidad',       8500.00,'Hardware'),
(1002,'MacBook Pro M2 16" (Para Devs iOS)',    'Equipo especializado para compilación Apple',      'Unidad',      18000.00,'Hardware'),
(1003,'Suscripción AWS EC2 t3.large (Anual)',  'Máquina Virtual en la nube',                       'Suscripción',  8500.00,'Cloud'),
(1004,'Suscripción AWS RDS PostgreSQL (Anual)', 'Base de datos administrada en AWS',                'Suscripción', 12000.00,'Cloud'),
(1005,'Licencia Figma Professional (Anual)',   'Herramienta de diseño UI/UX colaborativo',         'Licencia',     1800.00,'Software'),
(1006,'Switch Cisco Catalyst 24 Puertos PoE',  'Switch para proveer energía a teléfonos y APs',   'Unidad',       8500.00,'Redes');

INSERT INTO PROYECTO (id_proyecto, nombre_proyecto, descripcion, fecha_inicio, fecha_fin_estimada, fecha_fin_real, presupuesto_total, estado, id_cliente, id_gerente) VALUES
(1001,'Sistema de Facturación Electrónica SIAT', 'Plataforma web de emisión de facturas integrada con Impuestos Nacionales vía SOAP/XML.', '2025-01-15','2025-06-15','2025-06-10', 220000.00,'Finalizada',  1001,1004),
(1002,'App Móvil Banca Joven', 'Aplicación nativa iOS/Android con transacciones, pago QR y consulta de saldo en tiempo real.', '2025-03-01','2025-08-01', NULL,         185000.00,'En Progreso', 1002,1004),
(1003,'Portal Web de Gestión de Siniestros', 'Portal para asegurados: carga de documentos, seguimiento de reclamos y resolución en línea.', '2025-06-10','2025-11-10', NULL,         130000.00,'En Progreso', 1003,1005),
(1004,'Migración de Infraestructura a AWS', 'Traslado completo de servidores on-premise a instancias EC2 y RDS usando AWS DMS.', '2024-10-01','2025-03-01','2025-03-05', 310000.00,'Finalizada',  1004,1005),
(1005,'App de Delivery con Geolocalización', 'Plataforma móvil para pedidos a domicilio con rastreo GPS en tiempo real de repartidores.', '2024-08-10','2025-01-10','2025-01-20', 275000.00,'Finalizada',  1005,1006),
(1006,'Portal de Trámites Académicos en Línea', 'Ventanilla virtual para solicitud de certificados, pagos de colegiatura y seguimiento académico.', '2025-04-20','2025-10-20', NULL,         190000.00,'Pendiente',   1006,1006);

-- ==========================================
-- FASE 6: INSERCIÓN EN TABLAS DEPENDIENTES PULIDAS
-- ==========================================
INSERT INTO ES_MIEMBRO (id_proyecto, id_usuario, rol_en_proyecto, fecha_ingreso) VALUES
(1001,1004,'Gerente de Proyecto',  '2025-01-15'), (1002,1004,'Gerente de Proyecto',  '2025-03-01'),
(1003,1005,'Gerente de Proyecto',  '2025-06-10'), (1004,1005,'Gerente de Proyecto',  '2024-10-01'),
(1005,1006,'Gerente de Proyecto',  '2024-08-10'), (1006,1006,'Gerente de Proyecto',  '2025-04-20'),
(1001,1007,'Líder Backend Node.js',    '2025-01-15'), (1001,1008,'Desarrolladora Frontend',  '2025-01-16'),
(1001,1009,'Administrador PostgreSQL', '2025-01-15'), (1001,1010,'Ingeniera QA',             '2025-02-01'),
(1001,1011,'Ingeniero DevOps',         '2025-01-15'), (1002,1012,'Diseñadora UI/UX',      '2025-03-01'),
(1002,1013,'Desarrollador Java',    '2025-03-10'), (1002,1015,'Desarrollador Android', '2025-03-10'),
(1002,1016,'Desarrolladora iOS',    '2025-03-15'), (1003,1007,'Integrador Backend',     '2025-06-10'),
(1003,1014,'Desarrolladora Angular', '2025-06-12'), (1003,1012,'Diseñadora UI',          '2025-06-10'),
(1003,1010,'QA Funcional',           '2025-07-01'), (1004,1011,'Ingeniero DevOps',    '2024-10-01'),
(1004,1017,'Ingeniero de Datos',  '2024-10-01'), (1004,1009,'DBA PostgreSQL',      '2024-11-01'),
(1004,1010,'QA Performance',      '2025-01-15'), (1005,1012,'Diseñadora de Interfaces','2024-08-10'),
(1005,1008,'Frontend React App',      '2024-08-15'), (1005,1015,'Desarrollador Android',   '2024-09-01'),
(1005,1007,'Backend Go (APIs)',        '2024-09-10'), (1005,1010,'QA de Campo',             '2024-12-01'),
(1006,1008,'Desarrolladora Frontend','2025-04-20'), (1006,1014,'Desarrolladora Angular', '2025-04-22'),
(1006,1009,'DBA PostgreSQL',         '2025-04-20'), (1006,1018,'Consultor de Procesos',  '2025-04-25');

INSERT INTO TAREA (id_tarea, titulo, descripcion, fecha_inicio, fecha_fin_estimada, fecha_fin_real, horas_estimadas, prioridad, estado, id_proyecto, id_usuario) VALUES
(1001,'Levantamiento de Requerimientos SIAT', 'Reuniones con stakeholders y redacción del documento funcional AS-IS y TO-BE.', '2025-01-15','2025-01-30','2025-01-28', 40,'Alta','Finalizada',1001,1007),
(1002,'Diseño del Modelo Entidad-Relación', 'Diagrama relacional, normalización a 3FN y scripts DDL para PostgreSQL.', '2025-01-20','2025-02-05','2025-02-02', 30,'Alta','Finalizada',1001,1009),
(1003,'Desarrollo de API REST en Node.js', 'Endpoints, autenticación JWT y conexión SOAP con Impuestos Nacionales.', '2025-02-01','2025-04-01','2025-03-28',160,'Alta','Finalizada',1001,1007),
(1004,'Maquetación e Integración Frontend React', 'Interfaces React + TailwindCSS integradas con la API REST.', '2025-02-15','2025-04-15','2025-04-12',160,'Media','Finalizada',1001,1008),
(1005,'Despliegue a Producción en AWS', 'Pipelines CI/CD, Dockerización y despliegue en instancias EC2.', '2025-05-15','2025-06-10','2025-06-08', 40,'Alta','Finalizada',1001,1011),
(1006,'Diseño UI/UX en Figma', 'Wireframes y prototipos de alta fidelidad para iOS y Android.', '2025-03-01','2025-03-20','2025-03-18', 60,'Media','Finalizada',1002,1012),
(1007,'Desarrollo de Microservicios Java Spring', 'Lógica transaccional con Spring Boot y conexión al core bancario AS400.', '2025-03-21','2025-06-21', NULL,        200,'Alta','En Progreso',1002,1013),
(1008,'Desarrollo App Android Kotlin', 'Vistas de transferencias, pago QR y consulta de saldo en Android nativo.', '2025-04-01','2025-07-01', NULL,        180,'Alta','En Progreso',1002,1015),
(1009,'Desarrollo App iOS Swift', 'Adaptación a lineamientos Apple y programación nativa en Swift.', '2025-04-15','2025-07-15', NULL,        180,'Alta','Pendiente',  1002,1016),
(1010,'Análisis de Procesos de Seguros', 'Mapeo de flujos de reclamos: siniestros automotores y de vida.', '2025-06-10','2025-06-30','2025-06-28', 60,'Media','Finalizada', 1003,1007),
(1011,'Arquitectura de Software y Base de Datos', 'Definición de patrones microservicios y modelo de datos relacional.', '2025-07-01','2025-07-15','2025-07-14', 40,'Alta','Finalizada',  1003,1009),
(1012,'Desarrollo Frontend con Angular', 'Módulos de carga de fotos, documentos y seguimiento de siniestros.', '2025-07-16','2025-09-16', NULL,        150,'Media','En Progreso',1003,1014),
(1013,'Desarrollo Backend Python FastAPI', 'Validación de pólizas e integración con la aseguradora vía REST.', '2025-07-16','2025-09-20', NULL,        150,'Alta','En Progreso', 1003,1007),
(1014,'Auditoría de Servidores Locales', 'Inventario de hardware on-premise y análisis de sizing para instancias cloud.', '2024-10-01','2024-10-15','2024-10-12', 40,'Alta','Finalizada',1004,1011),
(1015,'Creación de VPC y Políticas IAM', 'Redes privadas virtuales, subnets, security groups y roles IAM en AWS.', '2024-10-16','2024-11-16','2024-11-10', 80,'Alta','Finalizada',1004,1011),
(1016,'Migración de Datos con AWS DMS', 'Traslado de terabytes de información minimizando el downtime operativo.', '2024-11-20','2025-01-20','2025-01-15',120,'Alta','Finalizada',1004,1017),
(1017,'Pruebas de Carga y Auto-Scaling', 'Verificación de balanceadores ALB y respuesta del cluster bajo estrés.', '2025-01-21','2025-02-28','2025-02-25', 60,'Media','Finalizada',1004,1010),
(1018,'Diseño de Pantallas Móviles', 'Vistas del mapa en tiempo real, perfil del repartidor y carrito de compras.', '2024-08-10','2024-08-25','2024-08-22', 50,'Media','Finalizada',1005,1012),
(1019,'Programación API y Geolocalización', 'API Node.js con WebSockets para rastreo concurrente de repartidores.', '2024-08-26','2024-10-26','2024-10-30',140,'Alta','Finalizada', 1005,1007),
(1020,'Desarrollo Móvil Android (Cliente y Chofer)', 'Apps Android con integración de Google Maps SDK y rastreo GPS.', '2024-10-01','2024-12-10','2024-12-05',200,'Alta','Finalizada', 1005,1015),
(1021,'Pruebas de Campo GPS', 'Recorridos físicos para validar precisión de ETA y geocercas.', '2024-12-11','2025-01-10','2025-01-08', 60,'Alta','Finalizada', 1005,1010),
(1022,'Despliegue Final y Monitoreo', 'Publicación en Google Play, alertas y monitoreo de producción.', '2025-01-10','2025-01-20','2025-01-18', 30,'Media','Finalizada',1005,1011),
(1023,'Levantamiento de Requerimientos UCB', 'Talleres con secretaría y sistemas para mapear los trámites prioritarios.', '2025-04-20','2025-05-05', NULL, 40,'Alta','Pendiente',1006,1008),
(1024,'Diseño de Base de Datos y API REST', 'Modelo relacional de estudiantes, trámites y pagos. Endpoints RESTful.', '2025-05-06','2025-06-30', NULL,120,'Alta','Pendiente',1006,1009),
(1025,'Desarrollo Frontend del Portal', 'Solicitud de certificados, historial de trámites y pasarela de pagos.', '2025-07-01','2025-09-01', NULL,160,'Media','Pendiente',1006,1014),
(1026,'Pruebas de Aceptación y Capacitación', 'UAT con usuarios finales y capacitación al personal administrativo UCB.', '2025-09-10','2025-10-10', NULL, 50,'Baja','Pendiente',1006,1010);

INSERT INTO DEPENDE (id_tarea, id_tarea_previa) VALUES
(1002,1001),(1003,1002),(1004,1003),(1005,1004),
(1007,1006),(1008,1006),(1009,1007),
(1011,1010),(1012,1011),(1013,1011),
(1015,1014),(1016,1015),(1017,1016),
(1019,1018),(1020,1019),(1021,1020),(1022,1021),
(1024,1023),(1025,1024),(1026,1025);

INSERT INTO UTILIZA (id_proyecto, id_recurso, cantidad_usada, fecha_uso, observacion) VALUES
(1001,1001, 4,'2025-01-15','Laptops Dell para equipo backend, DBA y QA'),
(1001,1003, 2,'2025-01-20','Instancias AWS EC2 para entornos staging y producción'),
(1001,1005, 1,'2025-01-16','Licencia Figma para maquetación UI del portal de facturas'),
(1002,1001, 3,'2025-03-01','Laptops para desarrolladores Java, Android e iOS'),
(1002,1002, 2,'2025-03-01','MacBooks para compilación y firma de la app iOS Swift'),
(1002,1005, 2,'2025-03-05','Licencias Figma para diseño y prototipado de banca móvil'),
(1003,1001, 3,'2025-06-10','Laptops para equipo Angular, FastAPI y QA'),
(1003,1005, 2,'2025-06-12','Figma para diseño de formularios de siniestros'),
(1004,1001, 4,'2024-10-01','Laptops para ingenieros DevOps y de datos'),
(1004,1003, 3,'2024-10-05','Instancias EC2 para migración incremental y pruebas'),
(1004,1004, 1,'2024-11-15','RDS PostgreSQL administrada para la BD migrada'),
(1005,1001, 4,'2024-08-10','Laptops para backend Go, Android y QA'),
(1005,1002, 1,'2024-08-12','MacBook para compilar app iOS del repartidor'),
(1005,1003, 2,'2024-09-10','Instancias EC2 para API WebSocket de geolocalización'),
(1006,1001, 3,'2025-04-20','Laptops para frontend, DBA y consultor de procesos'),
(1006,1006, 2,'2025-04-22','Switches PoE para nueva sala de servidores de la UCB');

-- NOTA: AQUÍ ESTÁN LOS REGISTROS DE AVANCE CON EL ESTADO APROBADO O PENDIENTE INCORPORADO
INSERT INTO REGISTRO_AVANCE (fecha_reporte, horas_trabajadas, porcentaje_avance, detalle_trabajo, estado, id_tarea, id_usuario) VALUES
-- Tarea 1001
('2025-01-18', 12, 30, 'Entrevistas iniciales con el área contable y jefatura de sistemas.',  'Aprobado', 1001,1007),
('2025-01-22', 16, 65, 'AS-IS documentado. Inicio de redacción TO-BE.',                       'Aprobado', 1001,1007),
('2025-01-28', 12,100, 'Documento funcional TO-BE aprobado por el cliente BNB.',              'Aprobado', 1001,1007),
-- Tarea 1002
('2025-01-23', 10, 40, 'Diagrama ER preliminar con 8 entidades identificadas.',               'Aprobado', 1002,1009),
('2025-01-27', 12, 80, 'Normalización a 3FN completada. Revisión con el PM.',                'Aprobado', 1002,1009),
('2025-02-02',  8,100, 'Scripts DDL ejecutados correctamente en Docker.',                      'Aprobado', 1002,1009),
-- Tarea 1003
('2025-02-05', 30, 15, 'Estructura del proyecto Express.js con JWT montada.',                 'Aprobado', 1003,1007),
('2025-02-20', 40, 35, 'CRUD de clientes y productos de factura terminado.',                  'Aprobado', 1003,1007),
('2025-03-05', 40, 60, 'Módulo de emisión de facturas funcional.',                             'Aprobado', 1003,1007),
('2025-03-15', 30, 80, 'Integración SOAP con el entorno de pruebas de SIAT.',                 'Aprobado', 1003,1007),
('2025-03-28', 20,100, 'Integración SOAP en producción. Prueba exitosa con firma digital.',   'Aprobado', 1003,1007),
-- Tarea 1004
('2025-03-01', 25, 15, 'Estructura de proyecto Vite + React. Componentes base con TailwindCSS.', 'Aprobado', 1004,1008),
('2025-03-15', 35, 35, 'Formulario de emisión de factura con validaciones Zod.',              'Aprobado', 1004,1008),
('2025-03-28', 40, 60, 'Pantallas de listado e historial de facturas integradas con API.',    'Aprobado', 1004,1008),
('2025-04-08', 40, 85, 'Módulo de reportes PDF implementado con React-PDF.',                  'Aprobado', 1004,1008),
('2025-04-12', 20,100, 'Integración completa frontend-backend. Aprobado por QA.',             'Aprobado', 1004,1008),
-- Tarea 1005
('2025-05-20', 12, 40, 'Dockerfiles para backend y frontend creados y probados localmente.',  'Aprobado', 1005,1011),
('2025-06-02', 16, 75, 'Pipeline GitHub Actions: build → test → push a ECR.',                'Aprobado', 1005,1011),
('2025-06-08', 12,100, 'Despliegue exitoso en EC2. Dominio con HTTPS configurado.',           'Aprobado', 1005,1011),
-- Tarea 1006
('2025-03-05', 14, 45, 'Wireframes de pantallas de login, saldo y transferencias.',           'Aprobado', 1006,1012),
('2025-03-12', 16, 80, 'Prototipo de alta fidelidad con flujos de pago QR.',                  'Aprobado', 1006,1012),
('2025-03-18', 12,100, 'Componentes exportados a handoff en Figma. Dev mode activo.',         'Aprobado', 1006,1012),
-- Tarea 1007 (Dejado como Pendiente para ver en la interfaz del Gerente)
('2025-04-01', 40, 20, 'Microservicio de cuentas: balance y transacciones básicas.',          'Aprobado', 1007,1013),
('2025-04-20', 50, 45, 'Microservicio de pagos QR integrado con switch transaccional.',       'Pendiente', 1007,1013),
('2025-05-15', 45, 65, 'API Gateway configurado. Circuit breaker con Resilience4j.',          'Pendiente', 1007,1013),
-- Tarea 1008 (Dejado como Pendiente para ver en la interfaz del Gerente)
('2025-04-10', 30, 18, 'Pantallas de login y dashboard de cuentas.',                           'Aprobado', 1008,1015),
('2025-05-05', 40, 40, 'Integración con API de transacciones. Consumo con Retrofit.',         'Pendiente', 1008,1015),
('2025-05-25', 45, 62, 'Módulo de pagos QR con lector de cámara implementado.',               'Pendiente', 1008,1015),
-- Tarea 1010
('2025-06-15', 20, 50, 'Flujo de reclamo automotor mapeado con BPMN.',                        'Aprobado', 1010,1007),
('2025-06-22', 22, 80, 'Flujo de reclamos de vida y hogar documentados.',                     'Aprobado', 1010,1007),
('2025-06-28', 18,100, 'Documento de análisis aprobado por La Boliviana Ciacruz.',            'Aprobado', 1010,1007),
-- Tarea 1011
('2025-07-05', 20, 55, 'Diagrama C4 de contexto y contenedores definido.',                    'Aprobado', 1011,1009),
('2025-07-14', 20,100, 'Modelo de datos con 9 entidades. Scripts DDL revisados.',             'Aprobado', 1011,1009),
-- Tarea 1012 (Dejado como Pendiente para ver en la interfaz del Gerente)
('2025-07-20', 30, 20, 'Módulo de autenticación y perfil del asegurado.',                     'Aprobado', 1012,1014),
('2025-08-05', 40, 45, 'Formulario de apertura de siniestro con carga de imágenes.',         'Pendiente', 1012,1014),
('2025-08-20', 35, 68, 'Pantalla de seguimiento de estado del reclamo en tiempo real.',       'Pendiente', 1012,1014),
-- Tarea 1013 (Dejado como Pendiente para ver en la interfaz del Gerente)
('2025-07-22', 35, 22, 'Endpoints de registro y validación de pólizas.',                      'Aprobado', 1013,1007),
('2025-08-10', 40, 50, 'Integración con API externa de La Boliviana Ciacruz.',               'Pendiente', 1013,1007),
-- Tarea 1014
('2024-10-05', 20, 50, 'Inventario físico de 12 servidores Dell y HP.',                       'Aprobado', 1014,1011),
('2024-10-12', 20,100, 'Informe de sizing: recomendación de instancias EC2 y RDS.',           'Aprobado', 1014,1011),
-- Tarea 1015
('2024-10-20', 25, 40, 'VPC principal con subnets públicas y privadas en 2 AZs.',             'Aprobado', 1015,1011),
('2024-11-01', 30, 75, 'Security groups y NACLs configurados. VPN Site-to-Site operativa.',   'Aprobado', 1015,1011),
('2024-11-10', 25,100, 'Roles IAM con principio de mínimo privilegio. Revisión de seguridad.','Aprobado', 1015,1011),
-- Tarea 1016
('2024-11-25', 40, 25, 'Tarea DMS configurada. Primeras tablas maestras migradas.',           'Aprobado', 1016,1017),
('2024-12-15', 50, 55, 'Migración incremental: 70% de datos históricos transferidos.',        'Aprobado', 1016,1017),
('2025-01-10', 40, 85, 'Tablas transaccionales migradas. Validación de integridad referencial.','Aprobado', 1016,1017),
('2025-01-15', 30,100, 'Migración completa. Cero inconsistencias detectadas.',                'Aprobado', 1016,1017),
-- Tarea 1017
('2025-01-25', 20, 35, 'Scripts JMeter para simular 500 usuarios concurrentes.',              'Aprobado', 1017,1010),
('2025-02-10', 25, 70, 'Auto-scaling probado: escala de 2 a 8 instancias en 90 seg.',         'Aprobado', 1017,1010),
('2025-02-25', 15,100, 'ALB y health-checks validados. Informe de rendimiento entregado.',    'Aprobado', 1017,1010),
-- Tarea 1018
('2024-08-14', 20, 40, 'Flujos del cliente: buscar restaurante, armar pedido, pagar.',        'Aprobado', 1018,1012),
('2024-08-20', 20, 80, 'Flujos del chofer: aceptar pedido, rastreo activo, entrega.',         'Aprobado', 1018,1012),
('2024-08-22', 10,100, 'Prototipo Figma aprobado. Assets exportados al equipo dev.',          'Aprobado', 1018,1012),
-- Tarea 1019
('2024-09-05', 30, 20, 'Servidor WebSocket con Socket.io. Sala por pedido activo.',           'Aprobado', 1019,1007),
('2024-09-20', 35, 45, 'API REST de pedidos con autenticación y estados.',                    'Aprobado', 1019,1007),
('2024-10-10', 40, 70, 'Algoritmo de ruteo con Directions API de Google Maps.',               'Aprobado', 1019,1007),
('2024-10-30', 35,100, 'Optimización de latencia a menos de 200ms. Pruebas de carga ok.',    'Aprobado', 1019,1007),
-- Tarea 1020
('2024-10-08', 40, 20, 'Apps base Android (Cliente y Chofer) con navegación por tabs.',       'Aprobado', 1020,1015),
('2024-11-01', 55, 50, 'Integración SDK Google Maps con marcadores y rutas.',                 'Aprobado', 1020,1015),
('2024-11-20', 50, 75, 'Notificaciones push con FCM. Estados del pedido en tiempo real.',     'Aprobado', 1020,1015),
('2024-12-05', 55,100, 'MVP completo aprobado en demo con PedidosYa Bolivia.',                'Aprobado', 1020,1015),
-- Tarea 1021
('2024-12-15', 20, 40, 'Prueba de ruta: zona centro La Paz. ETA con 95% de precisión.',      'Aprobado', 1021,1010),
('2024-12-22', 20, 75, 'Prueba en zona sur y El Alto. Geocercas de restaurantes calibradas.', 'Aprobado', 1021,1010),
('2025-01-08', 20,100, 'Prueba final: 20 pedidos reales. Tiempo promedio entrega: 28 min.',  'Aprobado', 1021,1010),
-- Tarea 1022
('2025-01-12', 15, 50, 'Preparación del APK firmado y políticas Google Play.',                'Aprobado', 1022,1011),
('2025-01-18', 15,100, 'App publicada en Google Play. Alertas CloudWatch activas.',           'Aprobado', 1022,1011);

INSERT INTO COMENTARIO (id_comentario, contenido, fecha_comentario, id_tarea, id_usuario) VALUES
(1001,'Subí el PR con la estructura base de Express, JWT y middleware de errores. Por favor revisar rama feature/api-base.',  '2025-02-06 09:00:00',1003,1007),
(1002,'Revisado. Buena estructura. Falta agregar logger con Winston para trazabilidad de auditoría fiscal.',                  '2025-02-06 14:30:00',1003,1009),
(1003,'Logger añadido con niveles info/warn/error y rotación diaria de archivos. Hago merge a develop.',                     '2025-02-07 09:15:00',1003,1007),
(1004,'Merge aprobado. Recuerden que el certificado SIAT de pruebas vence el 28/03. Renovar antes.',                         '2025-02-07 16:00:00',1003,1004),
(1005,'Anotado. Creo tarea en Jira para renovación del certificado. Ya coordiné con el equipo de SIAT.',                     '2025-02-08 08:30:00',1003,1009),
(1006,'El formulario de emisión tarda 3s en cargar los ítems de la factura. Necesita paginación o lazy load.',               '2025-03-20 10:00:00',1004,1010),
(1007,'Implementé virtualización con TanStack Virtual. Ahora carga 1000 ítems en menos de 300ms.',                           '2025-03-21 09:30:00',1004,1008),
(1008,'Confirmado en QA. El reporte de rendimiento muestra mejora del 90%. Aprobado para staging.',                          '2025-03-21 15:00:00',1004,1010),
(1009,'El microservicio de transferencias necesita validar saldo disponible antes del commit. Riesgo de saldo negativo.',    '2025-04-20 11:00:00',1007,1009),
(1010,'Confirmo. Implementé optimistic locking con @Version en JPA. El test de concurrencia con 100 hilos pasa sin errores.','2025-04-21 09:30:00',1007,1013),
(1011,'Excelente solución. Agregar también una alerta cuando el tiempo de respuesta supere 800ms en producción.',            '2025-04-21 14:00:00',1007,1005),
(1012,'Alerta Micrometer + Prometheus configurada. Umbral en 800ms con notificación a Slack del equipo.',                    '2025-04-22 10:15:00',1007,1013),
(1013,'Perfecto. Documenten esto en el README del microservicio para futuros devs.',                                         '2025-04-22 11:30:00',1007,1004),
(1014,'El lector QR falla en ambientes con poca luz. Probé 3 librerías y ML Kit de Google da mejores resultados.',           '2025-05-10 09:15:00',1008,1015),
(1015,'Migrado a ML Kit Vision. La tasa de lectura en condiciones oscuras mejoró de 40% a 95%. PR en revisión.',             '2025-05-11 10:00:00',1008,1015),
(1016,'PR aprobado. Excelente investigación Héctor. Actualizar la sección de dependencias en el CHANGELOG.',                 '2025-05-12 08:30:00',1008,1013),
(1017,'La subida de imágenes falla con archivos mayores a 5MB. El backend rechaza la petición con 413.',                     '2025-08-08 09:00:00',1012,1010),
(1018,'Configuro el límite de body en FastAPI a 20MB y agrego compresión de imágenes en el frontend.',                       '2025-08-08 11:30:00',1012,1014),
(1019,'Listo y probado. Los PDFs de hasta 15MB también pasan. Manual de usuario actualizado.',                               '2025-08-09 09:00:00',1012,1007),
(1020,'La API de La Boliviana devuelve error 504 intermitentemente. Necesitamos retry y circuit breaker.',                   '2025-08-12 10:00:00',1013,1007),
(1021,'Implementé tenacity para retry con backoff exponencial (3 intentos, máx 30s). Circuit breaker con pybreaker.',        '2025-08-13 09:00:00',1013,1007),
(1022,'Probado en staging con 200 solicitudes simuladas. Tasa de éxito: 99.5%. Aprobado por el PM.',                        '2025-08-14 14:00:00',1013,1005),
(1023,'El volcado inicial de las tablas de historial tardó 6 horas. El DMS está saturando el ancho de banda.',               '2024-12-10 08:00:00',1016,1017),
(1024,'Implementaré cargas delta con filtro por columna updated_at. Reduce el tiempo a 20 minutos por tabla.',              '2024-12-10 09:30:00',1016,1011),
(1025,'Cargas delta funcionando. La migración nocturna completa ahora tarda 35 minutos. Sin impacto en producción.',         '2024-12-18 08:00:00',1016,1017),
(1026,'Excelente resultado. Documentar el proceso en la wiki de arquitectura.',                                              '2024-12-18 10:00:00',1016,1005),
(1027,'Los WebSockets se desconectan cuando la app Android pasa a segundo plano en MIUI y One UI.',                          '2024-10-20 09:15:00',1019,1015),
(1028,'Implementé heartbeat ping/pong cada 15 segundos desde el servidor. También reconexión automática en el cliente.',     '2024-10-21 10:00:00',1019,1007),
(1029,'Funciona perfecto. La conexión persiste incluso con la pantalla apagada. Probé con 50 clientes simultáneos.',         '2024-10-21 16:30:00',1019,1015),
(1030,'Documentar este comportamiento en la guía de integración móvil. Es un problema común en Android con Doze Mode.',      '2024-10-22 09:00:00',1019,1006);

INSERT INTO NOTIFICACION (id_notificacion, tipo_alerta, titulo, mensaje, fecha_generacion, leido, id_usuario, id_referencia, nivel_prioridad) VALUES
(1001,'ASIGNACION','Asignado al proyecto: Facturación SIAT', 'Has sido asignado como Líder Backend al proyecto "Sistema de Facturación Electrónica SIAT". Fecha de inicio: 15/01/2025.', '2025-01-15 08:05:00',TRUE, 1007,1001,'Normal'),
(1002,'ASIGNACION','Asignado al proyecto: Facturación SIAT', 'Has sido asignada como Desarrolladora Frontend al proyecto "Sistema de Facturación Electrónica SIAT". Fecha de inicio: 16/01/2025.', '2025-01-16 08:05:00',TRUE, 1008,1001,'Normal'),
(1003,'ASIGNACION','Asignado al proyecto: App Banca Joven', 'Has sido asignado como Desarrollador Java al proyecto "App Móvil Banca Joven". Inicio: 10/03/2025.', '2025-03-10 08:00:00',TRUE, 1013,1002,'Normal'),
(1004,'ASIGNACION','Asignado al proyecto: App Banca Joven', 'Has sido asignado como Desarrollador Android al proyecto "App Móvil Banca Joven". Inicio: 10/03/2025.', '2025-03-10 08:00:00',TRUE, 1015,1002,'Normal'),
(1005,'ASIGNACION','Asignada nueva tarea: Desarrollo App iOS Swift', 'Se te ha asignado la tarea "Desarrollo App iOS Swift" en el proyecto Banca Joven. Fecha límite: 15/07/2025.', '2025-04-15 09:00:00',FALSE,1016,1009,'Normal'),
(1006,'ASIGNACION','Asignado al proyecto: Portal de Siniestros', 'Has sido asignada como Desarrolladora Angular al proyecto "Portal Web de Gestión de Siniestros". Inicio: 12/06/2025.', '2025-06-12 08:10:00',TRUE, 1014,1003,'Normal'),
(1007,'ASIGNACION','Asignado al proyecto: Migración AWS', 'Has sido asignado como Ingeniero de Datos al proyecto "Migración de Infraestructura a AWS". Inicio: 01/10/2024.', '2024-10-01 08:05:00',TRUE, 1017,1004,'Normal'),
(1008,'ASIGNACION','Asignado al proyecto: Portal Trámites UCB', 'Has sido asignado como Consultor de Procesos al proyecto "Portal de Trámites Académicos en Línea". Inicio: 25/04/2025.', '2025-04-25 08:10:00',FALSE,1018,1006,'Normal'),
(1009,'RETRASO_TAREA','Tarea retrasada: Desarrollo API REST', 'La tarea "Desarrollo de API REST en Node.js" superó su fecha estimada (01/04/2025) sin ser finalizada. Revisar avance.', '2025-04-02 07:00:00',TRUE, 1004,1003,'Advertencia'),
(1010,'RETRASO_TAREA','Tarea retrasada: Programación API Delivery', 'La tarea "Programación API y Geolocalización" superó su fecha estimada (26/10/2024). Impacto potencial en el cronograma.', '2024-10-27 07:00:00',TRUE, 1006,1019,'Advertencia'),
(1011,'RETRASO_TAREA','Tarea retrasada: Microservicios Java Spring', 'La tarea "Desarrollo de Microservicios Java Spring" lleva 3 semanas sin actualización de avance. Porcentaje actual: 65%.', '2025-06-25 07:00:00',FALSE,1004,1007,'Advertencia'),
(1012,'RETRASO_TAREA','Tarea retrasada: Desarrollo Frontend Angular', 'La tarea "Desarrollo Frontend con Angular" supera la mitad del tiempo estimado con 68% de avance. Riesgo de no cumplir fecha.', '2025-09-17 07:00:00',FALSE,1005,1012,'Advertencia'),
(1013,'RETRASO_TAREA','Tarea sin iniciar: Desarrollo App iOS Swift', 'La tarea "Desarrollo App iOS Swift" no registra avance tras 15 días de su fecha de inicio (15/04/2025).', '2025-04-30 07:00:00',FALSE,1006,1009,'Critica'),
(1014,'RETRASO_TAREA','Alerta crítica: tarea vencida', 'La tarea "Desarrollo Backend Python FastAPI" venció el 20/09/2025 con 50% de avance. Se requiere reunión de contingencia.', '2025-09-21 07:00:00',FALSE,1005,1013,'Critica'),
(1015,'LIMITE_PRESUPUESTO','Presupuesto al 75%: Facturación SIAT', 'El proyecto "Sistema de Facturación Electrónica SIAT" ha consumido el 75% de su presupuesto (Bs. 165.000 de Bs. 220.000).', '2025-04-15 09:00:00',TRUE, 1004,1001,'Advertencia'),
(1016,'LIMITE_PRESUPUESTO','Presupuesto al 90%: Migración AWS', 'El proyecto "Migración de Infraestructura a AWS" ha alcanzado el 90% de su presupuesto (Bs. 279.000 de Bs. 310.000).', '2025-02-01 09:00:00',TRUE, 1005,1004,'Critica'),
(1017,'LIMITE_PRESUPUESTO','Presupuesto al 60%: App Delivery', 'El proyecto "App de Delivery con Geolocalización" consumió el 60% del presupuesto en el primer cuatrimestre.', '2024-12-05 09:00:00',TRUE, 1006,1005,'Normal'),
(1018,'LIMITE_PRESUPUESTO','Presupuesto al 80%: App Banca Joven', 'El proyecto "App Móvil Banca Joven" ha superado el 80% de presupuesto con 3 meses restantes. Evaluar contingencia.', '2025-06-01 09:00:00',FALSE,1004,1002,'Advertencia'),
(1019,'LIMITE_PRESUPUESTO','Presupuesto al 70%: Portal Siniestros', 'El proyecto "Portal Web de Gestión de Siniestros" consumió Bs. 91.000 de Bs. 130.000. Ritmo dentro del margen.', '2025-09-10 09:00:00',FALSE,1005,1003,'Normal'),
(1020,'SISTEMA','Mantenimiento programado del sistema', 'El sistema estará en mantenimiento el sábado 25/01/2025 de 22:00 a 02:00. Guarde su trabajo antes del corte.', '2025-01-24 17:00:00',TRUE, 1001,NULL,'Normal'),
(1021,'SISTEMA','Mantenimiento programado del sistema', 'El sistema estará en mantenimiento el sábado 25/01/2025 de 22:00 a 02:00. Guarde su trabajo antes del corte.', '2025-01-24 17:00:00',TRUE, 1002,NULL,'Normal'),
(1022,'SISTEMA','Mantenimiento programado del sistema', 'El sistema estará en mantenimiento el sábado 25/01/2025 de 22:00 a 02:00. Guarde su trabajo antes del corte.', '2025-01-24 17:00:00',TRUE, 1003,NULL,'Normal'),
(1023,'SISTEMA','Nueva versión de la plataforma disponible: v2.4.0', 'Se desplegó la versión 2.4.0 con mejoras en el dashboard KPI, exportación a Excel y correcciones de seguridad.', '2025-05-10 08:00:00',TRUE, 1001,NULL,'Normal'),
(1024,'SISTEMA','Nueva versión de la plataforma disponible: v2.4.0', 'Se desplegó la versión 2.4.0 con mejoras en el dashboard KPI, exportación a Excel y correcciones de seguridad.', '2025-05-10 08:00:00',FALSE,1004,NULL,'Normal'),
(1025,'SISTEMA','Nueva versión de la plataforma disponible: v2.4.0', 'Se desplegó la versión 2.4.0 con mejoras en el dashboard KPI, exportación a Excel y correcciones de seguridad.', '2025-05-10 08:00:00',FALSE,1005,NULL,'Normal'),
(1026,'SISTEMA','Política de contraseñas actualizada', 'A partir del 01/06/2025 las contraseñas deben tener mínimo 12 caracteres, una mayúscula y un carácter especial.', '2025-05-28 10:00:00',TRUE, 1002,NULL,'Advertencia'),
(1027,'SISTEMA','Recordatorio: entrega de informe mensual de avance', 'Los gerentes de proyecto deben entregar el informe de avance de mayo antes del viernes 06/06/2025.', '2025-06-03 08:00:00',TRUE, 1004,NULL,'Normal'),
(1028,'SISTEMA','Recordatorio: entrega de informe mensual de avance', 'Los gerentes de proyecto deben entregar el informe de avance de mayo antes del viernes 06/06/2025.', '2025-06-03 08:00:00',FALSE,1006,NULL,'Normal');

INSERT INTO HISTORIAL_ESTADO (id_historial, tabla_referencia, id_referencia, estado_anterior, estado_nuevo, fecha_cambio, id_usuario) VALUES
(1001,'PROYECTO',1001,'Pendiente',  'En Progreso','2025-01-15 08:00:00',1004),
(1002,'PROYECTO',1001,'En Progreso','Finalizada', '2025-06-10 18:30:00',1004),
(1003,'PROYECTO',1002,'Pendiente',  'En Progreso','2025-03-01 09:15:00',1004),
(1004,'PROYECTO',1003,'Pendiente',  'En Progreso','2025-06-10 08:45:00',1005),
(1005,'PROYECTO',1004,'Pendiente',  'En Progreso','2024-10-01 08:00:00',1005),
(1006,'PROYECTO',1004,'En Progreso','Finalizada', '2025-03-05 17:00:00',1005),
(1007,'PROYECTO',1005,'Pendiente',  'En Progreso','2024-08-10 08:15:00',1006),
(1008,'PROYECTO',1005,'En Progreso','Finalizada', '2025-01-20 16:45:00',1006),
(1009, 'TAREA',1001,'Pendiente',  'En Progreso','2025-01-15 09:30:00',1007),
(1010, 'TAREA',1001,'En Progreso','Finalizada', '2025-01-28 16:45:00',1007),
(1011, 'TAREA',1002,'Pendiente',  'En Progreso','2025-01-20 10:00:00',1009),
(1012, 'TAREA',1002,'En Progreso','Finalizada', '2025-02-02 11:20:00',1009),
(1013, 'TAREA',1003,'Pendiente',  'En Progreso','2025-02-01 08:30:00',1007),
(1014, 'TAREA',1003,'En Progreso','Finalizada', '2025-03-28 18:00:00',1007),
(1015, 'TAREA',1004,'Pendiente',  'En Progreso','2025-02-15 09:15:00',1008),
(1016, 'TAREA',1004,'En Progreso','Finalizada', '2025-04-12 17:30:00',1008),
(1017, 'TAREA',1005,'Pendiente',  'En Progreso','2025-05-15 10:00:00',1011),
(1018, 'TAREA',1005,'En Progreso','Finalizada', '2025-06-08 14:20:00',1011),
(1019, 'TAREA',1006,'Pendiente',  'En Progreso','2025-03-01 08:30:00',1012),
(1020, 'TAREA',1006,'En Progreso','Finalizada', '2025-03-18 16:00:00',1012),
(1021, 'TAREA',1007,'Pendiente',  'En Progreso','2025-03-21 09:00:00',1013),
(1022, 'TAREA',1008,'Pendiente',  'En Progreso','2025-04-01 10:15:00',1015),
(1023, 'TAREA',1010,'Pendiente',  'En Progreso','2025-06-10 09:00:00',1007),
(1024, 'TAREA',1010,'En Progreso','Finalizada', '2025-06-28 16:00:00',1007),
(1025, 'TAREA',1011,'Pendiente',  'En Progreso','2025-07-01 09:00:00',1009),
(1026, 'TAREA',1011,'En Progreso','Finalizada', '2025-07-14 17:00:00',1009),
(1027, 'TAREA',1012,'Pendiente',  'En Progreso','2025-07-16 08:30:00',1014),
(1028, 'TAREA',1013,'Pendiente',  'En Progreso','2025-07-16 09:00:00',1007),
(1029, 'TAREA',1014,'Pendiente',  'En Progreso','2024-10-01 08:30:00',1011),
(1030, 'TAREA',1014,'En Progreso','Finalizada', '2024-10-12 16:10:00',1011),
(1031, 'TAREA',1015,'Pendiente',  'En Progreso','2024-10-16 09:00:00',1011),
(1032, 'TAREA',1015,'En Progreso','Finalizada', '2024-11-10 14:45:00',1011),
(1033, 'TAREA',1016,'Pendiente',  'En Progreso','2024-11-20 08:15:00',1017),
(1034, 'TAREA',1016,'En Progreso','Finalizada', '2025-01-15 17:00:00',1017),
(1035, 'TAREA',1017,'Pendiente',  'En Progreso','2025-01-21 09:30:00',1010),
(1036, 'TAREA',1017,'En Progreso','Finalizada', '2025-02-25 15:20:00',1010),
(1037, 'TAREA',1018,'Pendiente',  'En Progreso','2024-08-10 08:00:00',1012),
(1038, 'TAREA',1018,'En Progreso','Finalizada', '2024-08-22 16:30:00',1012),
(1039, 'TAREA',1019,'Pendiente',  'En Progreso','2024-08-26 09:15:00',1007),
(1040, 'TAREA',1019,'En Progreso','Finalizada', '2024-10-30 15:00:00',1007),
(1041, 'TAREA',1020,'Pendiente',  'En Progreso','2024-10-01 10:00:00',1015),
(1042, 'TAREA',1020,'En Progreso','Finalizada', '2024-12-05 14:45:00',1015),
(1043, 'TAREA',1021,'Pendiente',  'En Progreso','2024-12-11 08:30:00',1010),
(1044, 'TAREA',1021,'En Progreso','Finalizada', '2025-01-08 16:20:00',1010),
(1045, 'TAREA',1022,'Pendiente',  'En Progreso','2025-01-10 09:00:00',1011),
(1046, 'TAREA',1022,'En Progreso','Finalizada', '2025-01-18 15:00:00',1011),
(1047, 'TAREA',1023,'Pendiente',  'En Progreso','2025-04-20 10:00:00',1008),
(1048, 'TAREA',1023,'En Progreso','Pendiente',  '2025-04-21 16:00:00',1003);

-- ==========================================
-- SINCRONIZACIÓN DE SECUENCIAS
-- ==========================================
SELECT setval(pg_get_serial_sequence('usuario',           'id_usuario'),      COALESCE((SELECT MAX(id_usuario)        FROM usuario),          1),true);
SELECT setval(pg_get_serial_sequence('cliente',           'id_cliente'),      COALESCE((SELECT MAX(id_cliente)        FROM cliente),          1),true);
SELECT setval(pg_get_serial_sequence('recurso_material',  'id_recurso'),      COALESCE((SELECT MAX(id_recurso)        FROM recurso_material), 1),true);
SELECT setval(pg_get_serial_sequence('proyecto',          'id_proyecto'),     COALESCE((SELECT MAX(id_proyecto)       FROM proyecto),         1),true);
SELECT setval(pg_get_serial_sequence('tarea',             'id_tarea'),        COALESCE((SELECT MAX(id_tarea)          FROM tarea),            1),true);
SELECT setval(pg_get_serial_sequence('registro_avance',   'id_registro'),     COALESCE((SELECT MAX(id_registro)       FROM registro_avance),  1),true);
SELECT setval(pg_get_serial_sequence('comentario',        'id_comentario'),   COALESCE((SELECT MAX(id_comentario)     FROM comentario),       1),true);
SELECT setval(pg_get_serial_sequence('notificacion',      'id_notificacion'), COALESCE((SELECT MAX(id_notificacion)   FROM notificacion),     1),true);
SELECT setval(pg_get_serial_sequence('historial_estado',  'id_historial'),    COALESCE((SELECT MAX(id_historial)      FROM historial_estado), 1),true);