-- ==========================================
-- FASE 1: LIMPIEZA DE TABLAS (CASCADE para evitar errores de llaves)
-- ==========================================
DROP TABLE IF EXISTS HISTORIAL_ESTADO CASCADE;
DROP TABLE IF EXISTS MENSAJE CASCADE;
DROP TABLE IF EXISTS COMENTARIO CASCADE;
DROP TABLE IF EXISTS UTILIZA CASCADE;
DROP TABLE IF EXISTS RECURSO_MATERIAL CASCADE;
DROP TABLE IF EXISTS REGISTRO_AVANCE CASCADE;
DROP TABLE IF EXISTS DEPENDE CASCADE;
DROP TABLE IF EXISTS TAREA CASCADE;
DROP TABLE IF EXISTS ES_MIEMBRO CASCADE;
DROP TABLE IF EXISTS PROYECTO CASCADE;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;

-- ==========================================
-- FASE 2: CREACIÓN DE TABLAS MAESTRAS
-- ==========================================

-- ==========================================
-- FASE 1: CREACIÓN DE TABLAS MAESTRAS
-- PostgreSQL (IDENTITY en lugar de SERIAL)
-- ==========================================

CREATE TABLE USUARIO (
id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ci VARCHAR(20) UNIQUE NOT NULL,
nombre VARCHAR(100) NOT NULL,
apellido_paterno VARCHAR(100) NOT NULL,
apellido_materno VARCHAR(100),
fecha_nacimiento DATE,
sexo CHAR(1) CHECK (sexo IN ('M', 'F')),
telefono VARCHAR(50),
direccion TEXT,
correo VARCHAR(100) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL,
rol VARCHAR(50) NOT NULL,
especialidad VARCHAR(100),
costo_por_hora DECIMAL(10,2) DEFAULT 0.00,
foto_perfil TEXT,
fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE CLIENTE (
id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_empresa VARCHAR(150) NOT NULL,
nit VARCHAR(50) UNIQUE NOT NULL,
telefono_contacto VARCHAR(50),
correo_empresa VARCHAR(100),
direccion_empresa TEXT,
fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE RECURSO_MATERIAL (
id_recurso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_recurso VARCHAR(150) NOT NULL,
descripcion TEXT,
unidad_medida VARCHAR(50),
costo_unitario DECIMAL(12,2) NOT NULL,
categoria VARCHAR(100)
);

-- ==========================================
-- FASE 2: CREACIÓN DE TABLAS TRANSACCIONALES
-- ==========================================

CREATE TABLE PROYECTO (
id_proyecto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_proyecto VARCHAR(200) NOT NULL,
descripcion TEXT,
fecha_inicio DATE NOT NULL,
fecha_fin_estimada DATE,
fecha_fin_real DATE,
presupuesto_total DECIMAL(12,2) NOT NULL,
estado VARCHAR(50) DEFAULT 'Pendiente'
CHECK (estado IN ('Pendiente', 'En Progreso', 'Finalizada', 'Cancelado')),
fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
id_cliente INTEGER REFERENCES CLIENTE(id_cliente) ON DELETE RESTRICT,
id_gerente INTEGER REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);

CREATE TABLE TAREA (
id_tarea INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
titulo VARCHAR(200) NOT NULL,
descripcion TEXT,
fecha_inicio DATE NOT NULL,
fecha_fin_estimada DATE,
fecha_fin_real DATE,
horas_estimadas INTEGER NOT NULL CHECK (horas_estimadas > 0),
prioridad VARCHAR(50) DEFAULT 'Media'
CHECK (prioridad IN ('Baja', 'Media', 'Alta')),
estado VARCHAR(50) DEFAULT 'Pendiente'
CHECK (estado IN ('Pendiente', 'En Progreso', 'Finalizada', 'Cancelada')),
id_proyecto INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE,
id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);

-- ==========================================
-- FASE 3: TABLAS INTERMEDIAS Y DETALLE
-- ==========================================

CREATE TABLE ES_MIEMBRO (
id_proyecto INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE,
id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
rol_en_proyecto VARCHAR(100),
fecha_ingreso DATE DEFAULT CURRENT_DATE,
PRIMARY KEY (id_proyecto, id_usuario)
);

CREATE TABLE DEPENDE (
id_tarea INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
id_tarea_previa INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
PRIMARY KEY (id_tarea, id_tarea_previa),
CHECK (id_tarea <> id_tarea_previa)
);

CREATE TABLE REGISTRO_AVANCE (
id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
fecha_reporte DATE DEFAULT CURRENT_DATE,
horas_trabajadas NUMERIC(5,2) NOT NULL CHECK (horas_trabajadas > 0),
porcentaje_avance INTEGER
CHECK (porcentaje_avance BETWEEN 0 AND 100),
detalle_trabajo TEXT,
id_tarea INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
);

CREATE TABLE UTILIZA (
id_proyecto INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE,
id_recurso INTEGER REFERENCES RECURSO_MATERIAL(id_recurso) ON DELETE CASCADE,
cantidad_usada INTEGER NOT NULL CHECK (cantidad_usada > 0),
fecha_uso DATE DEFAULT CURRENT_DATE,
observacion TEXT,
PRIMARY KEY (id_proyecto, id_recurso)
);

CREATE TABLE COMENTARIO (
id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
contenido TEXT NOT NULL,
fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
id_tarea INTEGER REFERENCES TAREA(id_tarea) ON DELETE CASCADE,
id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE
);

CREATE TABLE MENSAJE (
id_mensaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
contenido TEXT NOT NULL,
fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
leido BOOLEAN DEFAULT FALSE,
id_remitente INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
id_destinatario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE CASCADE,
id_proyecto INTEGER REFERENCES PROYECTO(id_proyecto) ON DELETE CASCADE
);

CREATE TABLE HISTORIAL_ESTADO (
id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tabla_referencia VARCHAR(50) NOT NULL,
id_referencia INTEGER NOT NULL,
estado_anterior VARCHAR(50),
estado_nuevo VARCHAR(50) NOT NULL,
fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
id_usuario INTEGER REFERENCES USUARIO(id_usuario) ON DELETE SET NULL
);


-- ==========================================
-- FASE 5: INYECCIÓN DE DATOS MAESTROS (USUARIOS)
-- ==========================================

-- Insertar Usuarios (IDs inician en 1001)
INSERT INTO USUARIO (id_usuario, ci, nombre, apellido_paterno, apellido_materno, fecha_nacimiento, sexo, telefono, direccion, correo, password_hash, rol, especialidad, costo_por_hora) VALUES
-- Administradores
(1001, '8345612', 'Roberto', 'Alarcón', 'Méndez', '1985-04-12', 'M', '71234567', 'Av. Arce #123, Edificio Empresarial', 'r.alarcon@innovasoft.bo', 'pass_seguro_1', 'Admin', 'Infraestructura TI', 0.00),
(1002, '9123845', 'Valeria', 'Cárdenas', 'Ríos', '1990-08-25', 'F', '79823411', 'Calle 21 de Calacoto #45', 'v.cardenas@innovasoft.bo', 'pass_seguro_2', 'Admin', 'Seguridad y Accesos', 0.00),
(1003, '6452391', 'Marcelo', 'Quiroga', 'Paz', '1982-11-03', 'M', '61239844', 'Av. Bush #902', 'm.quiroga@innovasoft.bo', 'pass_seguro_3', 'Admin', 'Auditoría de Sistemas', 0.00),

-- Gerentes de Proyecto (PMs)
(1004, '7531982', 'Andrea', 'Soliz', 'Vaca', '1988-01-15', 'F', '77521099', 'Av. 6 de Agosto #1020', 'a.soliz@innovasoft.bo', 'gerente_123', 'Gerente', 'Gestión Ágil (Scrum)', 180.00),
(1005, '8642109', 'Diego', 'Torrez', 'Salinas', '1986-07-22', 'M', '76451233', 'Zona Sur, Obrajes Calle 10', 'd.torrez@innovasoft.bo', 'gerente_123', 'Gerente', 'Proyectos Cloud', 190.50),
(1006, '5321487', 'Camila', 'Vargas', 'López', '1992-05-10', 'F', '71548766', 'Sopocachi, Calle Ecuador #33', 'c.vargas@innovasoft.bo', 'gerente_123', 'Gerente', 'Desarrollo Móvil', 175.00),
(1007, '9876543', 'Javier', 'Mendoza', 'Soto', '1980-09-30', 'M', '69871234', 'Miraflores, Av. Saavedra', 'j.mendoza@innovasoft.bo', 'gerente_123', 'Gerente', 'Sistemas Financieros', 200.00),
(1008, '4567891', 'Lucía', 'Fernández', 'Cruz', '1991-12-05', 'F', '78901234', 'Av. Costanera #500', 'l.fernandez@innovasoft.bo', 'gerente_123', 'Gerente', 'Implementación ERP', 185.00),
(1009, '3216549', 'Rodrigo', 'Salazar', 'Montes', '1987-03-18', 'M', '76543210', 'Calle Comercio #88', 'r.salazar@innovasoft.bo', 'gerente_123', 'Gerente', 'Migración de Datos', 170.00),
(1010, '1597534', 'Paola', 'Espinoza', 'Roca', '1993-02-28', 'F', '71223344', 'Av. 20 de Octubre #211', 'p.espinoza@innovasoft.bo', 'gerente_123', 'Gerente', 'Desarrollo Web Fullstack', 195.00),

-- Empleados (Desarrolladores, QA, Diseñadores)
(1011, '8523697', 'Miguel Ángel', 'Castro', 'Silva', '1995-06-12', 'M', '77711223', 'Alto Obrajes Sector A', 'm.castro@innovasoft.bo', 'emp_pass_1', 'Empleado', 'Backend Node.js', 90.00),
(1012, '7412589', 'Sofía', 'Ramírez', 'Luna', '1997-10-04', 'F', '65432109', 'Irpavi II, Calle 4', 's.ramirez@innovasoft.bo', 'emp_pass_2', 'Empleado', 'Frontend React', 85.00),
(1013, '9632587', 'Carlos', 'Llanos', 'Pérez', '1990-01-20', 'M', '78965412', 'Achumani, Calle 22', 'c.llanos@innovasoft.bo', 'emp_pass_3', 'Empleado', 'DBA PostgreSQL', 110.00),
(1014, '1239874', 'Elena', 'Poma', 'Quispe', '1994-08-15', 'F', '71122334', 'Av. Buenos Aires #1500', 'e.poma@innovasoft.bo', 'emp_pass_4', 'Empleado', 'QA Automation', 80.00),
(1015, '4561237', 'Julio César', 'Ruiz', 'García', '1992-11-25', 'M', '62233445', 'Cota Cota, Calle 30', 'j.ruiz@innovasoft.bo', 'emp_pass_5', 'Empleado', 'DevOps Docker/AWS', 120.00),
(1016, '7894561', 'Daniela', 'Arce', 'Mora', '1996-03-08', 'F', '73344556', 'San Miguel, Bloque B', 'd.arce@innovasoft.bo', 'emp_pass_6', 'Empleado', 'UI/UX Designer Figma', 75.00),
(1017, '3217896', 'Luis Fernando', 'Choque', 'Mamani', '1993-07-14', 'M', '74455667', 'Villa Fátima, Plaza Principal', 'l.choque@innovasoft.bo', 'emp_pass_7', 'Empleado', 'Backend Java Spring', 95.00),
(1018, '6541239', 'Gabriela', 'Montenegro', 'Díaz', '1998-09-02', 'F', '65566778', 'Sopocachi, Calle Rosendo', 'g.montenegro@innovasoft.bo', 'emp_pass_8', 'Empleado', 'Frontend Angular', 85.00),
(1019, '9873214', 'Héctor', 'Salinas', 'Vega', '1991-04-19', 'M', '76677889', 'Miraflores, Calle Díaz', 'h.salinas@innovasoft.bo', 'emp_pass_9', 'Empleado', 'Desarrollo Android Kotlin', 100.00),
(1020, '1472583', 'Mariana', 'Cortez', 'Rivas', '1995-12-11', 'F', '77788990', 'Av. 16 de Julio (Prado)', 'm.cortez@innovasoft.bo', 'emp_pass_10', 'Empleado', 'Desarrollo iOS Swift', 105.00),
(1021, '2583691', 'Andrés', 'Villarroel', 'Sanz', '1989-05-22', 'M', '68899001', 'Calacoto, Av. Ballivián', 'a.villarroel@innovasoft.bo', 'emp_pass_11', 'Empleado', 'Arquitectura de Software', 130.00),
(1022, '3691472', 'Natalia', 'Guzmán', 'Flores', '1990-10-09', 'F', '79900112', 'San Pedro, Plaza Sucre', 'n.guzman@innovasoft.bo', 'emp_pass_12', 'Empleado', 'Scrum Master', 115.00),
(1023, '1592634', 'Felipe', 'Ortiz', 'Castillo', '1994-02-14', 'M', '71011223', 'Av. Landaeta #88', 'f.ortiz@innovasoft.bo', 'emp_pass_13', 'Empleado', 'Analista de Requerimientos', 85.00),
(1024, '3571592', 'Carla', 'Condori', 'Apaza', '1996-08-01', 'F', '62122334', 'Villa Copacabana, Calle 1', 'c.condori@innovasoft.bo', 'emp_pass_14', 'Empleado', 'Backend Python Django', 90.00),
(1025, '8529631', 'Víctor Hugo', 'Paz', 'Estenssoro', '1992-01-30', 'M', '73233445', 'Av. periférica #330', 'v.paz@innovasoft.bo', 'emp_pass_15', 'Empleado', 'Seguridad Ofensiva', 125.00),
(1026, '7418529', 'Laura', 'Blanco', 'Villar', '1995-11-18', 'F', '74344556', 'Ciudad Satélite, Plan 561', 'l.blanco@innovasoft.bo', 'emp_pass_16', 'Empleado', 'Ciencia de Datos', 110.00),
(1027, '9637418', 'Ricardo', 'Medina', 'Soto', '1991-06-25', 'M', '65455667', 'El Alto, Cruce Viacha', 'r.medina@innovasoft.bo', 'emp_pass_17', 'Empleado', 'Ingeniero de Datos', 105.00),
(1028, '1236547', 'Silvia', 'Tellería', 'Ramos', '1998-03-12', 'F', '76566778', 'Achumani, Calle 15', 's.telleria@innovasoft.bo', 'emp_pass_18', 'Empleado', 'Soporte Técnico L2', 60.00),
(1029, '4569871', 'Esteban', 'Paredes', 'Gómez', '1993-09-05', 'M', '77677889', 'Obrajes, Calle 6', 'e.paredes@innovasoft.bo', 'emp_pass_19', 'Empleado', 'QA Manual', 70.00),
(1030, '7891234', 'Mónica', 'Lora', 'Paz', '1997-02-20', 'F', '68788990', 'Av. 20 de Octubre #110', 'm.lora@innovasoft.bo', 'emp_pass_20', 'Empleado', 'Diseño Gráfico', 75.00),
(1031, '3214569', 'Ignacio', 'Prado', 'Valdés', '1994-12-08', 'M', '79899001', 'Miraflores, Calle Villalobos', 'i.prado@innovasoft.bo', 'emp_pass_21', 'Empleado', 'Desarrollador Unity 3D', 95.00),
(1032, '6547891', 'Ximena', 'Alí', 'Rocha', '1996-05-15', 'F', '70911223', 'Zona Sur, Las Cholas', 'x.ali@innovasoft.bo', 'emp_pass_22', 'Empleado', 'Especialista SEO/SEM', 80.00),
(1033, '9871236', 'Bruno', 'Miranda', 'Soler', '1992-08-22', 'M', '61022334', 'Av. Arce, Torres Mall', 'b.miranda@innovasoft.bo', 'emp_pass_23', 'Empleado', 'Backend PHP Laravel', 85.00),
(1034, '1478523', 'Teresa', 'Silva', 'Campos', '1995-01-10', 'F', '72133445', 'Sopocachi, Av. Sánchez Lima', 't.silva@innovasoft.bo', 'emp_pass_24', 'Empleado', 'Frontend Vue.js', 85.00),
(1035, '2581479', 'Oscar', 'Velasco', 'Toro', '1990-11-28', 'M', '73244556', 'San Pedro, Calle Almirante Grau', 'o.velasco@innovasoft.bo', 'emp_pass_25', 'Empleado', 'Administrador Servidores', 115.00),
(1036, '3692581', 'Verónica', 'Justiniano', 'Viera', '1993-04-05', 'F', '64355667', 'Miraflores, Estado Mayor', 'v.justiniano@innovasoft.bo', 'emp_pass_26', 'Empleado', 'Desarrollo C# .NET', 95.00),
(1037, '1593574', 'Pablo', 'Zeballos', 'Ruiz', '1991-09-17', 'M', '75466778', 'Av. Camacho #100', 'p.zeballos@innovasoft.bo', 'emp_pass_27', 'Empleado', 'DBA Oracle', 110.00),
(1038, '3579512', 'Diana', 'Gutiérrez', 'Soria', '1997-06-21', 'F', '76577889', 'Av. 16 de Julio #33', 'd.gutierrez@innovasoft.bo', 'emp_pass_28', 'Empleado', 'Technical Writer', 70.00),
(1039, '8521479', 'Guillermo', 'Arias', 'Pino', '1994-03-30', 'M', '67688990', 'Alto Obrajes, Av. del Maestro', 'g.arias@innovasoft.bo', 'emp_pass_29', 'Empleado', 'Machine Learning', 130.00),
(1040, '7413698', 'Renata', 'Pinto', 'Lara', '1996-10-12', 'F', '78799001', 'San Antonio, Calle 1', 'r.pinto@innovasoft.bo', 'emp_pass_30', 'Empleado', 'Especialista PowerBI', 90.00),
(1041, '9638521', 'Joaquín', 'Cabrera', 'Mora', '1992-07-07', 'M', '79811223', 'Villa San Antonio Alto', 'j.cabrera@innovasoft.bo', 'emp_pass_31', 'Empleado', 'Backend Ruby on Rails', 95.00),
(1042, '1231478', 'Bárbara', 'Morales', 'Ríos', '1995-02-19', 'F', '60922334', 'Calacoto, Calle 18', 'b.morales@innovasoft.bo', 'emp_pass_32', 'Empleado', 'QA Performance', 85.00),
(1043, '4562589', 'Tomás', 'Aguilar', 'Sosa', '1989-12-25', 'M', '71033445', 'Av. Potosí #200', 't.aguilar@innovasoft.bo', 'emp_pass_33', 'Empleado', 'Consultor SAP', 140.00),
(1044, '7893692', 'Cecilia', 'Vargas', 'Roca', '1998-05-03', 'F', '72144556', 'Plaza Abaroa #15', 'c.vargas2@innovasoft.bo', 'emp_pass_34', 'Empleado', 'Frontend Svelte', 85.00),
(1045, '3211598', 'Leonardo', 'Tapia', 'Vaca', '1991-08-14', 'M', '63255667', 'Miraflores, Calle Cuba', 'l.tapia@innovasoft.bo', 'emp_pass_35', 'Empleado', 'Ingeniero Cloud Azure', 120.00),
(1046, '6542631', 'Alicia', 'Ríos', 'Lima', '1996-01-28', 'F', '74366778', 'Av. 6 de Agosto #150', 'a.rios@innovasoft.bo', 'emp_pass_36', 'Empleado', 'Diseñadora UI', 75.00),
(1047, '9873574', 'Eduardo', 'Molina', 'Cano', '1993-11-09', 'M', '75477889', 'Zona Sur, Las Florida', 'e.molina@innovasoft.bo', 'emp_pass_37', 'Empleado', 'Backend Go (Golang)', 105.00),
(1048, '1479512', 'Fabiola', 'Sánchez', 'Díaz', '1997-04-16', 'F', '66588990', 'El Alto, 16 de Julio', 'f.sanchez@innovasoft.bo', 'emp_pass_38', 'Empleado', 'Redes y Telecom.', 90.00),
(1049, '2587413', 'Marcos', 'Toledo', 'Rivas', '1994-09-22', 'M', '77699001', 'Av. Litoral #550', 'm.toledo@innovasoft.bo', 'emp_pass_39', 'Empleado', 'Soporte Técnico L3', 75.00),
(1050, '3698524', 'Jimena', 'Loza', 'Ortiz', '1998-12-01', 'F', '78711223', 'Av. Arce #112', 'j.loza@innovasoft.bo', 'emp_pass_40', 'Empleado', 'Documentadora', 65.00);




-- ==========================================
-- FASE 6: INYECCIÓN DE CLIENTES
-- ==========================================
INSERT INTO CLIENTE (id_cliente, nombre_empresa, nit, telefono_contacto, correo_empresa, direccion_empresa) VALUES
-- Sector Financiero y Bancario
(1001, 'Banco Mercantil Santa Cruz S.A.', '1028374020', '2112233', 'contacto@bmsc.com.bo', 'Av. Camacho, Edif. BMSC, La Paz'),
(1002, 'Banco Nacional de Bolivia (BNB)', '1011223340', '2123344', 'info@bnb.com.bo', 'Av. Camacho Esq. Colón, La Paz'),
(1003, 'Banco Unión S.A.', '1033445560', '2134455', 'soporte@bancounion.com.bo', 'Av. 16 de Julio, La Paz'),
(1004, 'Banco FIE S.A.', '1044556670', '2145566', 'consultas@bancofie.com.bo', 'Av. 6 de Agosto, La Paz'),
(1005, 'Banco de Crédito de Bolivia (BCP)', '1055667780', '2156677', 'contacto@bcp.com.bo', 'Av. Hernando Siles, Obrajes'),
(1006, 'La Boliviana Ciacruz Seguros', '1066778890', '2167788', 'atencion@lbc.com.bo', 'Av. 20 de Octubre, La Paz'),
(1007, 'Nacional Seguros Vida y Salud', '1077889900', '2178899', 'info@nacionalseguros.com.bo', 'Equipetrol, Santa Cruz'),
(1008, 'Bisa Seguros y Reaseguros S.A.', '1088990010', '2189900', 'contacto@bisaseguros.com.bo', 'Av. Arce, La Paz'),

-- Sector Telecomunicaciones y Tecnología
(1009, 'Empresa Nacional de Telecomunicaciones (ENTEL)', '1099001120', '2190011', 'corporativo@entel.bo', 'Calle Federico Zuazo, La Paz'),
(1010, 'Telecel S.A. (Tigo Bolivia)', '1100112230', '2201122', 'empresas@tigo.net.bo', 'Av. Doble Vía La Guardia, Santa Cruz'),
(1011, 'Nuevatel PCS de Bolivia (Viva)', '1111223340', '2212233', 'negocios@viva.com.bo', 'Av. República, Cochabamba'),
(1012, 'AXS Bolivia S.A.', '1122334450', '2223344', 'info@axsbolivia.com', 'Calle 15 de Calacoto, La Paz'),
(1013, 'Jalasoft Corporación', '1133445560', '77712345', 'contact@jalasoft.com', 'Parque Tecnológico, Cochabamba'),
(1014, 'Síntesis S.A.', '1144556670', '2245566', 'soporte@sintesis.com.bo', 'Av. Sánchez Lima, La Paz'),
(1015, 'Datec Ltda.', '1155667780', '2256677', 'info@datec.com.bo', 'Equipetrol Norte, Santa Cruz'),

-- Sector Retail y Comercio
(1016, 'Supermercados Ketal S.A.', '1166778890', '2267788', 'proveedores@ketal.com.bo', 'Av. Ballivián, Calacoto'),
(1017, 'Hipermaxi S.A.', '1177889900', '2278899', 'contacto@hipermaxi.com', 'Av. Banzer, Santa Cruz'),
(1018, 'Multicenter Bolivia', '1188990010', '2289900', 'atencion@multicenter.com.bo', '4to Anillo, Santa Cruz'),
(1019, 'Farmacias Chávez', '1199001120', '2290011', 'info@farmaciaschavez.com.bo', 'Av. Cañoto, Santa Cruz'),
(1020, 'Farmacorp S.A.', '1200112230', '2301122', 'contacto@farmacorp.com', 'Av. Cristo Redentor, Santa Cruz'),
(1021, 'Fair Play (Grupocom S.A.)', '1211223340', '2312233', 'info@fairplay.com.bo', 'Calle Comercio, La Paz'),
(1022, 'Dismac S.A.', '1222334450', '2323344', 'atencion@dismac.com.bo', 'Av. Grigotá, Santa Cruz'),
(1023, 'Hansa Ltda.', '1233445560', '2334455', 'hansa@hansa.com.bo', 'Calle Yanacocha, La Paz'),

-- Sector Industria, Construcción y Transporte
(1024, 'Cervecería Boliviana Nacional (CBN)', '1244556670', '2345566', 'info@cbn.bo', 'Av. Montes, La Paz'),
(1025, 'Sociedad Boliviana de Cemento (SOBOCE)', '1255667780', '2356677', 'contacto@soboce.com', 'Av. 16 de Julio, La Paz'),
(1026, 'Yacimientos Petrolíferos Fiscales Bolivianos (YPFB)', '1266778890', '2367788', 'institucional@ypfb.gob.bo', 'Av. 16 de Julio, La Paz'),
(1027, 'Pil Andina S.A.', '1277889900', '2378899', 'contacto@pilandina.com.bo', 'Km 10 Blanco Galindo, Cochabamba'),
(1028, 'Empresa Nacional de Electricidad (ENDE)', '1288990010', '2389900', 'info@ende.bo', 'Av. Colombia, Cochabamba'),
(1029, 'Constructora Tauro S.A.', '1299001120', '2390011', 'proyectos@tauro.com.bo', 'Av. Arce, La Paz'),
(1030, 'Mi Teleférico (Empresa Estatal)', '1300112230', '2401122', 'info@miteleferico.bo', 'Estación Central, La Paz'),
(1031, 'Boliviana de Aviación (BoA)', '1311223340', '2412233', 'corporativo@boa.bo', 'Av. Simón López, Cochabamba'),
(1032, 'Avícola Sofía Ltda.', '1322334450', '2423344', 'info@sofia.com.bo', 'Parque Industrial, Santa Cruz'),
(1033, 'La Francesa S.A.', '1333445560', '2434455', 'ventas@lafrancesa.com.bo', 'El Alto, La Paz'),
(1034, 'Inti S.A. (Droguería)', '1344556670', '2445566', 'contacto@inti.com.bo', 'Av. Saavedra, La Paz'),
(1035, 'Laboratorios Bagó de Bolivia', '1355667780', '2456677', 'info@bago.com.bo', 'Av. 20 de Octubre, La Paz'),

-- Sector Salud y Educación
(1036, 'Hospital Arco Iris', '1366778890', '2467788', 'info@hospitalarcoiris.com', 'Villa Fátima, La Paz'),
(1037, 'Clínica Cemes', '1377889900', '2478899', 'contacto@cemes.com.bo', 'Av. 6 de Agosto, La Paz'),
(1038, 'Clínica del Sur', '1388990010', '2489900', 'info@clinicadelsur.com.bo', 'Obrajes, La Paz'),
(1039, 'Universidad Católica Boliviana (UCB)', '1399001120', '2490011', 'contacto@ucb.edu.bo', 'Av. 14 de Septiembre, La Paz'),
(1040, 'Universidad Privada Boliviana (UPB)', '1400112230', '2501122', 'info@upb.edu', 'Camino a Achocalla, La Paz'),
(1041, 'Escuela Militar de Ingeniería (EMI)', '1411223340', '2512233', 'contacto@emi.edu.bo', 'Irpavi, La Paz'),

-- Empresas Consultoras y de Servicios
(1042, 'PricewaterhouseCoopers (PwC) Bolivia', '1422334450', '2523344', 'contacto@pwc.com.bo', 'Av. Costanera, La Paz'),
(1043, 'KPMG Bolivia', '1433445560', '2534455', 'info@kpmg.com.bo', 'Equipetrol, Santa Cruz'),
(1044, 'Ernst & Young (EY) Bolivia', '1444556670', '2545566', 'eybolivia@ey.com', 'Av. Arce, La Paz'),
(1045, 'PedidosYa Bolivia S.A.', '1455667780', '77799888', 'contacto@pedidosya.com.bo', 'Av. San Martín, Santa Cruz'),
(1046, 'Grupo Empresarial Lafuente', '1466778890', '2567788', 'info@grupolafuente.com.bo', 'Urubó, Santa Cruz'),
(1047, 'Grupocentro (Gestión Inmobiliaria)', '1477889900', '2578899', 'ventas@grupocentro.bo', 'Calle 21 de Calacoto, La Paz'),
(1048, 'Saguapac (Cooperativa de Aguas)', '1488990010', '3589900', 'info@saguapac.com.bo', 'Av. Río Grande, Santa Cruz'),
(1049, 'Cámara Nacional de Comercio (CNC)', '1499001120', '2590011', 'cnc@cnc.bo', 'Av. Mariscal Santa Cruz, La Paz'),
(1050, 'Feria Exposición de Santa Cruz (FEXPOCRUZ)', '1500112230', '3601122', 'info@fexpocruz.com.bo', 'Av. Roca y Coronado, Santa Cruz');


-- ==========================================
-- FASE 7: INYECCIÓN DE RECURSOS MATERIALES
-- ==========================================
INSERT INTO RECURSO_MATERIAL (id_recurso, nombre_recurso, descripcion, unidad_medida, costo_unitario, categoria) VALUES
-- Hardware y Computadoras
(1001, 'Laptop Dell Latitude Core i7 16GB RAM', 'Equipo de alto rendimiento para desarrollo', 'Unidad', 8500.00, 'Hardware'),
(1002, 'Laptop Lenovo ThinkPad Core i5 8GB RAM', 'Equipo estándar para uso de oficina', 'Unidad', 6500.00, 'Hardware'),
(1003, 'MacBook Pro M2 16" (Para Devs iOS)', 'Equipo especializado para compilación Apple', 'Unidad', 18000.00, 'Hardware'),
(1004, 'Monitor LG 27" 4K UHD', 'Monitor de alta resolución para diseño UI/UX', 'Unidad', 2500.00, 'Hardware'),
(1005, 'Monitor Dell 24" FHD', 'Monitor secundario estándar', 'Unidad', 1200.00, 'Hardware'),

-- Servidores Físicos y Almacenamiento
(1006, 'Servidor HP ProLiant DL380 Gen10', 'Servidor físico para centro de datos local', 'Unidad', 45000.00, 'Infraestructura'),
(1007, 'Servidor Dell PowerEdge R740', 'Servidor de cómputo para virtualización', 'Unidad', 42000.00, 'Infraestructura'),
(1008, 'Disco Duro NAS Western Digital Red 8TB', 'Almacenamiento de red para backups', 'Unidad', 2100.00, 'Infraestructura'),
(1009, 'Disco Duro SSD Samsung EVO 1TB', 'Almacenamiento rápido para bases de datos', 'Unidad', 850.00, 'Infraestructura'),
(1010, 'Memoria RAM DDR4 16GB ECC para Servidor', 'Memoria con corrección de errores', 'Unidad', 1100.00, 'Infraestructura'),

-- Equipamiento de Redes e Infraestructura
(1011, 'Switch Cisco Catalyst 24 Puertos PoE', 'Switch para proveer energía a teléfonos y APs', 'Unidad', 8500.00, 'Redes'),
(1012, 'Switch Cisco Catalyst 48 Puertos GbE', 'Switch principal de distribución LAN', 'Unidad', 15000.00, 'Redes'),
(1013, 'Router Mikrotik Cloud Core CCR1009', 'Enrutador de borde corporativo', 'Unidad', 6000.00, 'Redes'),
(1014, 'Access Point Ubiquiti UniFi Pro Wi-Fi 6', 'Punto de acceso inalámbrico alta densidad', 'Unidad', 1400.00, 'Redes'),
(1015, 'Firewall Fortinet FortiGate 60F', 'Equipo de seguridad perimetral', 'Unidad', 11000.00, 'Redes'),
(1016, 'Rack Metálico Cerrado 42U para Servidores', 'Gabinete para montaje de equipos', 'Unidad', 3500.00, 'Infraestructura'),
(1017, 'Bobina Cable UTP Cat 6 (305 metros)', 'Cable de red para estructurado interior', 'Rollo', 950.00, 'Redes'),
(1018, 'Patch Panel 24 Puertos Cat 6', 'Panel de parcheo para ordenamiento', 'Unidad', 450.00, 'Redes'),
(1019, 'Organizador de Cables Horizontal 1U', 'Organizador plástico de rack', 'Unidad', 120.00, 'Redes'),
(1020, 'Caja de Conectores RJ45 (100 unidades)', 'Plugs de red', 'Caja', 180.00, 'Redes'),
(1021, 'UPS APC Smart-UPS 3000VA', 'Respaldo de energía para racks', 'Unidad', 4500.00, 'Infraestructura'),
(1022, 'UPS APC Back-UPS 1500VA', 'Respaldo de energía para estaciones de trabajo', 'Unidad', 2200.00, 'Infraestructura'),

-- Licencias de Software y Seguridad
(1023, 'Licencia Windows Server 2022 (Standard)', 'Sistema Operativo Servidor', 'Licencia', 6500.00, 'Software'),
(1024, 'Licencia SQL Server 2022 (Core)', 'Licencia de Motor Base de Datos', 'Licencia', 25000.00, 'Software'),
(1025, 'Licencia VMware vSphere Standard', 'Plataforma de virtualización', 'Licencia', 8200.00, 'Software'),
(1026, 'Licencia Antivirus Kaspersky Endpoint (10 PCs)', 'Protección de estaciones de trabajo', 'Licencia', 2500.00, 'Software'),
(1027, 'Licencia Odoo Enterprise (Anual/Usuario)', 'Suscripción a ERP Odoo', 'Suscripción', 1500.00, 'Software'),
(1028, 'Certificado SSL Wildcard (Anual)', 'Seguridad encriptación Web', 'Suscripción', 1200.00, 'Software'),
(1029, 'Dominio Web .com.bo (Anual)', 'Registro de nombre en NIC Bolivia', 'Suscripción', 980.00, 'Infraestructura'),
(1030, 'Google Workspace Enterprise (Anual/Usuario)', 'Suite de correos y ofimática', 'Suscripción', 2100.00, 'Software'),

-- Servicios Cloud (AWS / Azure)
(1031, 'Suscripción AWS EC2 t3.large (Anual)', 'Máquina Virtual en la nube', 'Suscripción', 8500.00, 'Cloud'),
(1032, 'Suscripción AWS RDS PostgreSQL (Anual)', 'Base de datos administrada', 'Suscripción', 12000.00, 'Cloud'),
(1033, 'Suscripción AWS S3 Storage 1TB (Anual)', 'Almacenamiento de objetos', 'Suscripción', 1800.00, 'Cloud'),
(1034, 'Suscripción Microsoft Azure VM (Anual)', 'Máquina Virtual Azure', 'Suscripción', 9000.00, 'Cloud'),

-- Herramientas de Desarrollo y Diseño
(1035, 'Licencia Figma Professional (Anual)', 'Herramienta de Diseño de Interfaces', 'Suscripción', 1100.00, 'Software'),
(1036, 'Licencia JetBrains IntelliJ IDEA (Anual)', 'IDE de desarrollo Java/Kotlin', 'Suscripción', 1300.00, 'Software'),
(1037, 'Suscripción GitHub Copilot Business (Anual)', 'Asistente de IA para programadores', 'Suscripción', 1600.00, 'Software'),
(1038, 'Suscripción Docker Pro (Anual/Usuario)', 'Herramienta de contenedores', 'Suscripción', 450.00, 'Software'),

-- Equipos de Testing y QA
(1039, 'Smartphone Samsung Galaxy S23 (Test Android)', 'Dispositivo móvil para QA', 'Unidad', 7000.00, 'Testing'),
(1040, 'iPhone 14 Pro (Test iOS)', 'Dispositivo Apple para QA', 'Unidad', 9500.00, 'Testing'),
(1041, 'Tablet iPad Air (Test UI/UX)', 'Dispositivo tablet para diseño adaptable', 'Unidad', 5500.00, 'Testing'),

-- Seguridad Física y Oficina
(1042, 'Cámara de Seguridad IP Hikvision 4MP', 'Cámara CCTV', 'Unidad', 450.00, 'Oficina'),
(1043, 'NVR Hikvision 16 Canales para CCTV', 'Grabador de cámaras', 'Unidad', 1800.00, 'Oficina'),
(1044, 'Proyector Epson Inalámbrico 1080p', 'Proyector para salas de reuniones', 'Unidad', 5500.00, 'Oficina'),
(1045, 'Pizarra de Vidrio Templado (2x1m)', 'Pizarra para arquitectura de software', 'Unidad', 800.00, 'Oficina'),
(1046, 'Escritorio Operativo Tipo L', 'Mobiliario de oficina', 'Unidad', 1200.00, 'Oficina'),
(1047, 'Silla Ergonómica Ejecutiva', 'Mobiliario de oficina', 'Unidad', 950.00, 'Oficina'),
(1048, 'Impresora Multifuncional HP LaserJet Pro', 'Impresora de red corporativa', 'Unidad', 3200.00, 'Oficina'),

-- Herramientas Especializadas de Hardware
(1049, 'Herramienta de Crimpeado RJ45 Profesional', 'Pinza para cables de red', 'Unidad', 250.00, 'Redes'),
(1050, 'Testeadora de Red Fluke Networks (Certificador)', 'Certificadora de cobre/fibra', 'Unidad', 18500.00, 'Redes');




-- ==========================================
-- FASE 8: INYECCIÓN DE PROYECTOS
-- ==========================================
INSERT INTO PROYECTO (id_proyecto, nombre_proyecto, descripcion, fecha_inicio, fecha_fin_estimada, fecha_fin_real, presupuesto_total, estado, id_cliente, id_gerente) VALUES
-- Proyectos del Gerente Andrea Soliz (ID: 1004)
(1001, 'Sistema de Facturación Electrónica en Línea (SIAT)', 'Desarrollo de plataforma web integral para facturación electrónica regulada por Impuestos Nacionales.', '2025-01-15', '2025-06-15', '2025-06-10', 120000.00, 'Finalizada', 1001, 1004),
(1002, 'Desarrollo de App Móvil Banca Joven', 'Aplicación móvil nativa (iOS/Android) orientada a la captación de clientes jóvenes del sector bancario.', '2025-03-01', '2025-08-30', NULL, 250000.00, 'En Progreso', 1002, 1004),
(1003, 'Portal de Autogestión de Seguros', 'Plataforma web para que los clientes puedan reportar siniestros y descargar pólizas de forma autónoma.', '2025-06-10', '2025-11-10', NULL, 185000.00, 'En Progreso', 1006, 1004),
(1004, 'Implementación de Pasarela de Pagos E-commerce', 'Integración de múltiples métodos de pago (Tarjetas, QR) para la plataforma de ventas online.', '2025-08-01', '2025-12-01', NULL, 95000.00, 'Pendiente', 1016, 1004),
(1005, 'Sistema de Control de Asistencia Biométrico', 'Software de control de personal conectado a relojes biométricos ZKTeco en múltiples sucursales.', '2024-02-10', '2024-05-10', '2024-05-15', 45000.00, 'Finalizada', 1024, 1004),
(1006, 'Plataforma B2B para Distribuidores', 'Portal para la toma de pedidos mayoristas, control de stock y seguimiento de despachos.', '2025-09-15', '2026-03-15', NULL, 160000.00, 'Pendiente', 1025, 1004),
(1007, 'Sistema de Gestión de Almacenes (WMS)', 'Software para la gestión de ubicaciones en estantes, picking y packing con terminales de radiofrecuencia.', '2025-02-20', '2025-07-20', NULL, 135000.00, 'En Progreso', 1018, 1004),

-- Proyectos del Gerente Diego Torrez (ID: 1005)
(1008, 'Migración de Infraestructura On-Premise a AWS', 'Traslado completo de servidores físicos, bases de datos y aplicaciones legacy a la nube de Amazon.', '2024-10-01', '2025-02-28', '2025-03-05', 320000.00, 'Finalizada', 1009, 1005),
(1009, 'Implementación de Data Lake Corporativo', 'Construcción de repositorio centralizado de datos estructurados y no estructurados para Business Intelligence.', '2025-01-20', '2025-09-20', NULL, 450000.00, 'En Progreso', 1010, 1005),
(1010, 'Despliegue de Servidores en Alta Disponibilidad (HA)', 'Configuración de clústeres de servidores con balanceo de carga para sistemas críticos 24/7.', '2025-04-10', '2025-06-10', NULL, 110000.00, 'En Progreso', 1011, 1005),
(1011, 'Auditoría y Optimización de Costos Cloud', 'Revisión de arquitectura en la nube para reducir gastos operativos y eliminar recursos inactivos.', '2025-07-01', '2025-08-15', NULL, 35000.00, 'Pendiente', 1012, 1005),
(1012, 'Migración de Bases de Datos Oracle a PostgreSQL RDS', 'Conversión de esquemas, procedimientos almacenados y datos de Oracle a un entorno Open Source gestionado.', '2024-05-15', '2024-11-15', '2024-12-01', 190000.00, 'Finalizada', 1014, 1005),
(1013, 'Implementación de Arquitectura Microservicios', 'Refactorización del monolito principal utilizando contenedores Docker y orquestación con Kubernetes.', '2025-05-01', '2025-12-30', NULL, 380000.00, 'En Progreso', 1015, 1005),
(1014, 'Sistema de Backups y Recuperación ante Desastres', 'Diseño de políticas de retención, respaldos inmutables y simulacros de recuperación (Disaster Recovery).', '2025-10-01', '2025-11-30', NULL, 75000.00, 'Pendiente', 1019, 1005),

-- Proyectos de la Gerente Camila Vargas (ID: 1006)
(1015, 'App Móvil de Delivery y Tracking de Pedidos', 'Desarrollo de ecosistema móvil (App Cliente y App Repartidor) con seguimiento GPS en tiempo real.', '2024-08-10', '2025-01-10', '2025-01-20', 180000.00, 'Finalizada', 1045, 1006),
(1016, 'Renovación de Interfaz App Mi Teleférico', 'Rediseño integral de la experiencia de usuario (UX/UI) de la aplicación de transporte masivo.', '2025-02-01', '2025-06-30', NULL, 150000.00, 'En Progreso', 1030, 1006),
(1017, 'Aplicación Móvil para Control de Inventarios', 'App interna para realizar conteos cíclicos usando la cámara del smartphone como lector de códigos de barras.', '2025-05-15', '2025-09-15', NULL, 90000.00, 'En Progreso', 1020, 1006),
(1018, 'Desarrollo de Billetera Móvil (Wallet)', 'Creación de aplicación financiera para transacciones P2P, pagos QR y recargas de saldo virtual.', '2024-11-01', '2025-04-30', '2025-05-05', 280000.00, 'Finalizada', 1003, 1006),
(1019, 'App de Telemedicina y Citas Médicas', 'Plataforma móvil para programación de consultas virtuales y videollamadas médicas encriptadas.', '2025-07-15', '2025-12-15', NULL, 210000.00, 'Pendiente', 1036, 1006),
(1020, 'Sistema de Rutas y Logística para Choferes', 'Algoritmo de enrutamiento dinámico para flotas de distribución minimizando tiempos y distancias.', '2025-03-10', '2025-08-10', NULL, 130000.00, 'En Progreso', 1032, 1006),
(1021, 'App Educativa e-Learning', 'Aplicación móvil con descarga de contenido offline, evaluaciones interactivas y emisión de certificados.', '2025-09-01', '2026-02-28', NULL, 165000.00, 'Pendiente', 1039, 1006),

-- Proyectos del Gerente Javier Mendoza (ID: 1007)
(1022, 'Core Bancario: Módulo de Créditos de Vivienda', 'Modernización del motor de cálculo de amortizaciones, flujos de aprobación y desembolsos de créditos.', '2024-01-10', '2024-10-10', '2024-11-05', 550000.00, 'Finalizada', 1004, 1007),
(1023, 'Sistema de Prevención de Lavado de Dinero (AML)', 'Implementación de algoritmos de Machine Learning para detectar transacciones financieras anómalas.', '2025-02-15', '2025-10-15', NULL, 420000.00, 'En Progreso', 1005, 1007),
(1024, 'Automatización de Conciliaciones Bancarias', 'Sistema para el cruce masivo de extractos SWIFT contra registros contables internos de la empresa.', '2025-04-01', '2025-07-30', NULL, 125000.00, 'En Progreso', 1007, 1007),
(1025, 'Plataforma de Trading y Bonos Corporativos', 'Portal web seguro para la negociación de títulos valores, acciones y bonos en el mercado bursátil local.', '2025-08-10', '2026-04-10', NULL, 310000.00, 'Pendiente', 1008, 1007),
(1026, 'Sistema de Gestión de Activos Fijos', 'Módulo contable para llevar el registro, depreciación y revalorización de bienes de uso de la organización.', '2024-06-01', '2024-09-30', '2024-10-02', 85000.00, 'Finalizada', 1026, 1007),
(1027, 'Integración de Cobros con QR Interoperable', 'Adecuación de sistemas de cajas para generar y procesar pagos mediante el estándar QR Simple.', '2025-05-20', '2025-08-20', NULL, 140000.00, 'En Progreso', 1017, 1007),
(1028, 'Tableros de Inteligencia de Negocios Financiera', 'Construcción de dashboards ejecutivos en PowerBI para analizar rentabilidad, mora y liquidez.', '2025-10-01', '2026-01-30', NULL, 95000.00, 'Pendiente', 1042, 1007),

-- Proyectos de la Gerente Lucía Fernández (ID: 1008)
(1029, 'Implementación SAP S/4HANA Módulo FI-CO', 'Despliegue integral de los módulos de Finanzas y Controlling del ERP de clase mundial SAP.', '2024-03-01', '2024-12-30', '2025-01-15', 680000.00, 'Finalizada', 1027, 1008),
(1030, 'Desarrollo de ERP a Medida para Retail', 'Construcción desde cero de un sistema de planificación de recursos empresariales enfocado en supermercados.', '2025-01-10', '2025-11-10', NULL, 450000.00, 'En Progreso', 1021, 1008),
(1031, 'Migración de Odoo v12 a Odoo v16', 'Actualización de versión del ERP, refactorización de módulos personalizados y migración de base de datos.', '2025-04-15', '2025-07-15', NULL, 90000.00, 'En Progreso', 1022, 1008),
(1032, 'Módulo de Recursos Humanos y Planillas', 'Automatización del cálculo de planillas salariales, aportes AFPs, RC-IVA y beneficios sociales.', '2025-06-01', '2025-10-01', NULL, 115000.00, 'Pendiente', 1046, 1008),
(1033, 'Integración de ERP con Sistema de Facturación', 'Enlace automatizado entre el módulo de ventas del ERP y los servicios web de Impuestos Nacionales.', '2024-09-10', '2024-12-10', '2024-12-20', 75000.00, 'Finalizada', 1023, 1008),
(1034, 'Sistema de Gestión Hospitalaria (HIS)', 'ERP enfocado en salud para gestión de pacientes, historias clínicas, quirófanos y farmacias.', '2025-03-20', '2025-12-20', NULL, 380000.00, 'En Progreso', 1037, 1008),
(1035, 'Automatización de Flujo de Compras', 'Sistema de requisiciones, cotizaciones, órdenes de compra y aprobaciones jerárquicas digitales.', '2025-09-01', '2025-11-30', NULL, 65000.00, 'Pendiente', 1048, 1008),

-- Proyectos del Gerente Rodrigo Salazar (ID: 1009)
(1036, 'Reestructuración de Topología de Red LAN/WAN', 'Rediseño de la infraestructura de red, cambio de cableado estructurado y segmentación de VLANs.', '2024-02-15', '2024-06-15', '2024-06-10', 150000.00, 'Finalizada', 1040, 1009),
(1037, 'Limpieza y Migración de Datos Históricos (ETL)', 'Procesos de Extracción, Transformación y Carga de bases de datos antiguas hacia el nuevo Data Warehouse.', '2025-01-05', '2025-05-05', '2025-05-12', 85000.00, 'Finalizada', 1028, 1009),
(1038, 'Implementación de Seguridad Perimetral (Firewalls)', 'Instalación de equipos Fortinet, creación de DMZ y túneles VPN IPsec para sucursales remotas.', '2025-04-01', '2025-07-01', NULL, 220000.00, 'En Progreso', 1031, 1009),
(1039, 'Auditoría de Ciberseguridad (Ethical Hacking)', 'Pruebas de intrusión externas e internas (Pentesting) para identificar y mitigar vulnerabilidades.', '2025-06-15', '2025-08-15', NULL, 70000.00, 'En Progreso', 1043, 1009),
(1040, 'Renovación de Equipamiento de Data Center', 'Cambio físico de servidores, storages, switches core y actualización de sistemas de energía ininterrumpida.', '2025-08-01', '2025-10-30', NULL, 340000.00, 'Pendiente', 1049, 1009),
(1041, 'Sistema de Monitoreo de Redes (NOC)', 'Implementación de centro de operaciones con pantallas y sistemas Zabbix para monitoreo proactivo.', '2024-11-20', '2025-03-20', '2025-03-25', 110000.00, 'Finalizada', 1013, 1009),
(1042, 'Central Telefónica IP (VoIP) Corporativa', 'Despliegue de central telefónica basada en Asterisk, con IVR interactivo y telefonía en la nube.', '2025-09-10', '2025-11-10', NULL, 60000.00, 'Pendiente', 1044, 1009),

-- Proyectos de la Gerente Paola Espinoza (ID: 1010)
(1043, 'Portal Web Institucional y Gestor de Contenidos', 'Desarrollo de sitio web corporativo con un CMS personalizado para la publicación ágil de noticias.', '2024-05-01', '2024-07-30', '2024-07-25', 45000.00, 'Finalizada', 1029, 1010),
(1044, 'Intranet Corporativa Moderna', 'Red social interna para empleados, con directorio telefónico, repositorio de documentos y foros.', '2025-02-10', '2025-06-10', NULL, 80000.00, 'En Progreso', 1033, 1010),
(1045, 'Sistema Web de Control de Flota de Vehículos', 'Aplicación para registrar mantenimientos, consumo de combustible y asignar vehículos a conductores.', '2025-03-15', '2025-08-15', NULL, 125000.00, 'En Progreso', 1034, 1010),
(1046, 'Plataforma de E-Learning para Capacitación Interna', 'Sistema de gestión de aprendizaje (LMS) para hospedar cursos, videos y evaluaciones del personal.', '2025-07-01', '2025-11-01', NULL, 105000.00, 'Pendiente', 1035, 1010),
(1047, 'Sistema CRM de Gestión de Clientes Web', 'Software para el seguimiento de leads, embudos de ventas y atención al cliente omnicanal.', '2024-08-15', '2024-12-15', '2024-12-28', 160000.00, 'Finalizada', 1047, 1010),
(1048, 'Portal de Trámites en Línea para Estudiantes', 'Ventanilla virtual para la solicitud de certificados, pagos de colegiatura y seguimiento académico.', '2025-04-20', '2025-09-20', NULL, 190000.00, 'En Progreso', 1041, 1010),
(1049, 'Sistema de Tickets de Soporte (HelpDesk)', 'Mesa de ayuda web para la categorización, asignación y resolución de incidentes técnicos (SLA).', '2025-09-05', '2025-11-05', NULL, 55000.00, 'Pendiente', 1050, 1010),
(1050, 'Automatización de Reservas de Laboratorios', 'Sistema para agendar el uso de espacios compartidos, controlar capacidad y autorizar accesos.', '2025-05-10', '2025-07-10', NULL, 40000.00, 'En Progreso', 1038, 1010);





-- ==========================================
-- FASE 9: ASIGNACIÓN MASIVA DE MIEMBROS A PROYECTOS (ES_MIEMBRO)
-- ==========================================

-- 2. Insertar a los Administradores como Auditores/Supervisores en proyectos clave
INSERT INTO ES_MIEMBRO (id_proyecto, id_usuario, rol_en_proyecto, fecha_ingreso) VALUES
(1001, 1001, 'Auditor TI', '2025-01-20'),
(1008, 1001, 'Asesor de Infraestructura', '2024-10-05'),
(1022, 1002, 'Auditora de Seguridad', '2024-01-15'),
(1039, 1002, 'Supervisora de Pentesting', '2025-06-20'),
(1029, 1003, 'Auditor Contable', '2024-03-10');

-- 3. Asignación Masiva del Equipo Técnico (Empleados 1011 al 1050)
INSERT INTO ES_MIEMBRO (id_proyecto, id_usuario, rol_en_proyecto, fecha_ingreso) VALUES
-- P-1001: Facturación (Web)
(1001, 1011, 'Líder Backend Node.js', '2025-01-15'),
(1001, 1012, 'Desarrolladora Frontend', '2025-01-16'),
(1001, 1013, 'Administrador PostgreSQL', '2025-01-15'),
(1001, 1014, 'Ingeniera QA', '2025-02-01'),
(1001, 1023, 'Analista Funcional', '2025-01-15'),

-- P-1002: Banca Joven (Mobile)
(1002, 1016, 'Diseñadora UI/UX', '2025-03-01'),
(1002, 1019, 'Líder Android', '2025-03-10'),
(1002, 1020, 'Líder iOS Swift', '2025-03-10'),
(1002, 1029, 'Tester QA Manual', '2025-04-01'),

-- P-1008: Migración AWS (Cloud)
(1008, 1015, 'Ingeniero DevOps', '2024-10-01'),
(1008, 1035, 'Admin Servidores Linux', '2024-10-01'),
(1008, 1045, 'Ingeniero Cloud Azure/AWS', '2024-10-15'),
(1008, 1027, 'Ingeniero de Datos', '2024-11-01'),

-- P-1015: App Delivery (Mobile & Maps)
(1015, 1022, 'Scrum Master', '2024-08-10'),
(1015, 1046, 'Diseñadora de Interfaces', '2024-08-15'),
(1015, 1047, 'Desarrollador Go (Rutas)', '2024-09-01'),
(1015, 1019, 'Desarrollador Android', '2024-09-10'),
(1015, 1042, 'QA Performance', '2024-10-01'),

-- P-1022: Core Bancario (Sistemas Críticos)
(1022, 1017, 'Arquitecto Java Spring', '2024-01-15'),
(1022, 1021, 'Arquitecto de Software', '2024-01-10'),
(1022, 1025, 'Especialista Ciberseguridad', '2024-02-01'),
(1022, 1037, 'DBA Oracle Senior', '2024-01-20'),
(1022, 1038, 'Technical Writer', '2024-08-01'),

-- P-1029: SAP S/4HANA (ERP)
(1029, 1043, 'Consultor SAP FI-CO', '2024-03-01'),
(1029, 1023, 'Levantamiento de Procesos', '2024-03-15'),
(1029, 1050, 'Documentadora', '2024-06-01'),

-- P-1036: Red LAN/WAN (Infraestructura)
(1036, 1048, 'Ingeniera de Redes', '2024-02-15'),
(1036, 1049, 'Soporte Técnico L3 (Routers)', '2024-03-01'),
(1036, 1028, 'Soporte L2 (Cableado)', '2024-03-15'),

-- P-1043: Portal Web Institucional
(1043, 1018, 'Desarrolladora Angular', '2024-05-01'),
(1043, 1034, 'Desarrolladora Vue.js', '2024-05-15'),
(1043, 1030, 'Diseñadora Gráfica', '2024-05-01'),
(1043, 1032, 'Especialista SEO', '2024-06-01'),

-- P-1009: Data Lake Corporativo
(1009, 1026, 'Científica de Datos', '2025-01-25'),
(1009, 1039, 'Ingeniero Machine Learning', '2025-02-10'),
(1009, 1040, 'Especialista PowerBI', '2025-03-01'),
(1009, 1027, 'Arquitecto de Datos', '2025-01-20'),

-- P-1031: Migración a Odoo v16 (ERP Python)
(1031, 1024, 'Desarrolladora Python', '2025-04-15'),
(1031, 1011, 'Integrador de APIs', '2025-05-01'),
(1031, 1014, 'Ingeniera QA', '2025-06-01'),

-- P-1049: Sistema de Tickets (HelpDesk)
(1049, 1041, 'Backend Ruby on Rails', '2025-09-05'),
(1049, 1034, 'Frontend Web', '2025-09-15'),
(1049, 1028, 'Soporte L2 (Pruebas Usuario)', '2025-10-01'),

-- P-1025: Plataforma de Trading Bursátil
(1025, 1036, 'Backend C# .NET', '2025-08-15'),
(1025, 1021, 'Arquitecto de Software', '2025-08-10'),
(1025, 1025, 'Seguridad Ofensiva', '2025-09-01'),

-- P-1021: App Educativa e-Learning y Videojuego
(1021, 1031, 'Desarrollador Unity 3D', '2025-09-05'),
(1021, 1016, 'Diseñadora UI', '2025-09-01'),
(1021, 1033, 'Backend PHP Laravel', '2025-09-15'),

-- Distribuir al resto de empleados para asegurar 100% de ocupación
(1003, 1033, 'Soporte Backend PHP', '2025-06-15'),
(1004, 1017, 'Integrador Pasarelas Java', '2025-08-05'),
(1005, 1048, 'Técnico Biométricos', '2024-02-15'),
(1006, 1041, 'Desarrollador Ruby', '2025-09-20'),
(1007, 1024, 'Backend Python', '2025-02-25'),
(1010, 1015, 'Especialista Docker', '2025-04-15'),
(1011, 1035, 'Auditor de Servidores', '2025-07-05'),
(1012, 1013, 'Especialista Postgres', '2024-05-20'),
(1013, 1021, 'Arquitecto Microservicios', '2025-05-10'),
(1014, 1045, 'Ingeniero de Backups AWS', '2025-10-05'),
(1018, 1020, 'Desarrolladora Swift iOS', '2024-11-10'),
(1019, 1019, 'Desarrollador WebRTC', '2025-07-20'),
(1020, 1047, 'Especialista Algoritmos Go', '2025-03-15'),
(1024, 1036, 'Integraciones C#', '2025-04-10'),
(1026, 1018, 'Desarrollo Frontend', '2024-06-10'),
(1027, 1011, 'Desarrollo Node.js API QR', '2025-05-25'),
(1028, 1040, 'Diseñadora de Dashboards', '2025-10-05'),
(1030, 1034, 'Frontend Vue.js', '2025-01-20'),
(1032, 1023, 'Especialista Planillas', '2025-06-10'),
(1033, 1033, 'Integrador Web Services', '2024-09-15'),
(1034, 1046, 'Diseñadora Interfaz Médica', '2025-04-01'),
(1035, 1044, 'Frontend Svelte', '2025-09-10'),
(1037, 1027, 'Especialista ETL', '2025-01-10'),
(1038, 1049, 'Configurador Fortinet', '2025-04-10'),
(1040, 1028, 'Soporte Montaje Racks', '2025-08-05'),
(1041, 1048, 'Configuración Zabbix NOC', '2024-11-25'),
(1042, 1035, 'Especialista Asterisk VoIP', '2025-09-15'),
(1044, 1030, 'Creativo Contenidos', '2025-02-15'),
(1045, 1012, 'Frontend React App Choferes', '2025-03-20'),
(1046, 1032, 'Promotora Plataforma', '2025-07-10'),
(1047, 1022, 'Scrum Master CRM', '2024-08-20'),
(1048, 1044, 'Desarrolladora Svelte', '2025-04-25'),
(1050, 1016, 'Diseño UI Pantallas Touch', '2025-05-15');




-- ==========================================
-- FASE 10: INYECCIÓN DE TAREAS
-- ==========================================
INSERT INTO TAREA (id_tarea, titulo, descripcion, fecha_inicio, fecha_fin_estimada, fecha_fin_real, horas_estimadas, prioridad, estado, id_proyecto, id_usuario) VALUES
-- ==========================================
-- PROYECTO 1001: Facturación (Finalizada)
-- ==========================================
(1001, 'Levantamiento de Requerimientos SIAT', 'Reuniones con stakeholders y redacción del documento funcional AS-IS y TO-BE.', '2025-01-15', '2025-01-30', '2025-01-28', 40, 'Alta', 'Finalizada', 1001, 1023),
(1002, 'Diseño del Modelo Entidad-Relación', 'Creación del diagrama relacional, normalización a 3FN y scripts DDL para PostgreSQL.', '2025-01-20', '2025-02-05', '2025-02-02', 30, 'Alta', 'Finalizada', 1001, 1013),
(1003, 'Desarrollo de API REST en Node.js', 'Programación de endpoints, autenticación JWT y conexión SOAP con Impuestos Nacionales.', '2025-02-01', '2025-04-01', '2025-03-28', 160, 'Alta', 'Finalizada', 1001, 1011),
(1004, 'Maquetación e Integración Frontend', 'Desarrollo de interfaces en React, TailwindCSS e integración con la API REST.', '2025-02-15', '2025-04-15', '2025-04-12', 160, 'Media', 'Finalizada', 1001, 1012),
(1005, 'Pruebas de Estrés y QA Automation', 'Creación de scripts en Cypress y pruebas de carga con JMeter simulando 1000 usuarios.', '2025-04-10', '2025-05-10', '2025-05-08', 80, 'Media', 'Finalizada', 1001, 1014),
(1006, 'Despliegue a Producción AWS', 'Configuración de pipelines CI/CD, Dockerización y despliegue en instancias EC2.', '2025-05-15', '2025-06-10', '2025-06-08', 40, 'Alta', 'Finalizada', 1001, 1015),

-- ==========================================
-- PROYECTO 1002: App Móvil Banca (En Progreso)
-- ==========================================
(1007, 'Diseño UI/UX en Figma', 'Creación de wireframes y prototipos interactivos de alta fidelidad para iOS y Android.', '2025-03-01', '2025-03-20', '2025-03-18', 60, 'Media', 'Finalizada', 1002, 1016),
(1008, 'Desarrollo de Microservicios Java', 'Programación de lógica de negocio transaccional con Spring Boot y conexión al AS400.', '2025-03-21', '2025-06-21', NULL, 200, 'Alta', 'En Progreso', 1002, 1017),
(1009, 'Desarrollo App Android Kotlin', 'Programación nativa de las vistas de transferencias, pago QR y consulta de saldo.', '2025-04-01', '2025-07-01', NULL, 180, 'Alta', 'En Progreso', 1002, 1019),
(1010, 'Desarrollo App iOS Swift', 'Adaptación del diseño UI a lineamientos de Apple y programación nativa en Swift.', '2025-04-01', '2025-07-01', NULL, 180, 'Alta', 'Pendiente', 1002, 1020),
(1011, 'Configuración de CI/CD', 'Creación de flujos de compilación automática en Bitbucket Pipelines y Fastlane.', '2025-03-15', '2025-04-15', '2025-04-12', 50, 'Media', 'Finalizada', 1002, 1015),

-- ==========================================
-- PROYECTO 1003: Portal Seguros (En Progreso)
-- ==========================================
(1012, 'Análisis de Procesos de Seguros', 'Mapeo de flujos de reclamos de siniestros automotores y vida.', '2025-06-10', '2025-06-30', '2025-06-28', 60, 'Media', 'Finalizada', 1003, 1023),
(1013, 'Arquitectura de Software y BD', 'Definición de patrones de diseño y estructura de microservicios para el portal.', '2025-07-01', '2025-07-15', '2025-07-14', 40, 'Alta', 'Finalizada', 1003, 1021),
(1014, 'Desarrollo Frontend con Angular', 'Implementación de vistas para que el asegurado suba fotos y documentos de su siniestro.', '2025-07-16', '2025-09-16', NULL, 150, 'Media', 'En Progreso', 1003, 1018),
(1015, 'Desarrollo Backend Python', 'Lógica de validación de pólizas, integraciones con aseguradora usando FastAPI.', '2025-07-16', '2025-09-16', NULL, 150, 'Alta', 'Pendiente', 1003, 1024),

-- ==========================================
-- PROYECTO 1008: Migración AWS (Finalizada)
-- ==========================================
(1016, 'Auditoría de Servidores Locales', 'Inventario de hardware on-premise y análisis de sizing para las instancias cloud.', '2024-10-01', '2024-10-15', '2024-10-12', 40, 'Alta', 'Finalizada', 1008, 1035),
(1017, 'Creación de VPC y Políticas IAM', 'Configuración de redes privadas virtuales, subnets y roles de acceso en AWS.', '2024-10-16', '2024-11-16', '2024-11-10', 80, 'Alta', 'Finalizada', 1008, 1045),
(1018, 'Migración de Datos y Bases de Datos', 'Uso de AWS DMS para mover terabytes de información minimizando el downtime.', '2024-11-20', '2025-01-20', '2025-01-15', 120, 'Alta', 'Finalizada', 1008, 1027),
(1019, 'Pruebas de Carga y Balanceadores', 'Verificación de auto-scaling y respuesta del Application Load Balancer bajo estrés.', '2025-01-21', '2025-02-28', '2025-02-25', 60, 'Media', 'Finalizada', 1008, 1042),

-- ==========================================
-- PROYECTO 1015: App Delivery (Finalizada)
-- ==========================================
(1020, 'Definición de Historias de Usuario', 'Priorización del backlog con el cliente y armado de los Sprints en Jira.', '2024-08-10', '2024-08-25', '2024-08-22', 40, 'Media', 'Finalizada', 1015, 1022),
(1021, 'Diseño de Pantallas Móviles', 'Diseño de la vista del mapa en tiempo real, perfil del chofer y carrito de compras.', '2024-08-26', '2024-09-15', '2024-09-10', 50, 'Media', 'Finalizada', 1015, 1046),
(1022, 'Programación API y Geolocalización', 'Desarrollo en Go para manejar conexiones websocket de miles de choferes concurrentes.', '2024-09-16', '2024-11-16', '2024-11-12', 140, 'Alta', 'Finalizada', 1015, 1047),
(1023, 'Desarrollo Móvil Cliente y Chofer', 'Implementación de ambas apps en Android, incluyendo integración con Google Maps SDK.', '2024-10-01', '2024-12-10', '2024-12-05', 200, 'Alta', 'Finalizada', 1015, 1019),
(1024, 'Pruebas de Campo GPS', 'Recorridos físicos en la ciudad para validar la precisión del cálculo de ETA y geocercas.', '2024-12-11', '2025-01-10', '2025-01-08', 60, 'Alta', 'Finalizada', 1015, 1029),

-- ==========================================
-- PROYECTO 1022: Core Bancario Créditos (Finalizada)
-- ==========================================
(1025, 'Reuniones de Negocio (Créditos)', 'Levantamiento de fórmulas de cálculo de interés francés, alemán y flat.', '2024-01-10', '2024-02-10', '2024-02-05', 80, 'Alta', 'Finalizada', 1022, 1023),
(1026, 'Diseño de Seguridad Transaccional', 'Análisis de vulnerabilidades y encriptación de datos sensibles de los deudores.', '2024-02-11', '2024-03-11', '2024-03-08', 80, 'Alta', 'Finalizada', 1022, 1025),
(1027, 'Implementación Lógica Financiera', 'Desarrollo profundo de los motores de cálculo y planes de pago en Java.', '2024-03-15', '2024-07-15', '2024-07-10', 300, 'Alta', 'Finalizada', 1022, 1017),
(1028, 'Pruebas Unitarias y Cobertura', 'Implementación de JUnit para garantizar 90% de cobertura en cálculos matemáticos.', '2024-07-16', '2024-09-16', '2024-09-12', 120, 'Media', 'Finalizada', 1022, 1014),
(1029, 'Documentación Técnica y Manuales', 'Creación de manuales de usuario para los oficiales de crédito y cajeros.', '2024-09-17', '2024-10-10', '2024-10-05', 60, 'Baja', 'Finalizada', 1022, 1038),

-- ==========================================
-- PROYECTO 1009: Data Lake Corporativo (En Progreso)
-- ==========================================
(1034, 'Modelado de Data Warehouse', 'Definición de modelo estrella, dimensiones y tablas de hechos para BI.', '2025-01-20', '2025-02-28', '2025-02-25', 100, 'Alta', 'Finalizada', 1009, 1026),
(1035, 'Creación de Pipelines ETL', 'Desarrollo de scripts para extracción automatizada de datos desde 5 sistemas origen distintos.', '2025-03-01', '2025-06-01', NULL, 200, 'Alta', 'En Progreso', 1009, 1027),
(1036, 'Implementación de Machine Learning', 'Entrenamiento de modelo predictivo para la fuga de clientes (Churn Rate).', '2025-04-15', '2025-07-15', NULL, 180, 'Alta', 'Pendiente', 1009, 1039),
(1037, 'Desarrollo de Dashboards en PowerBI', 'Creación de tableros directivos interactivos consumiendo datos del nuevo Data Lake.', '2025-06-01', '2025-08-01', NULL, 120, 'Media', 'Pendiente', 1009, 1040),
(1038, 'Afinamiento de Consultas SQL', 'Optimización de índices y particionamiento de tablas pesadas en Oracle.', '2025-03-15', '2025-05-15', NULL, 80, 'Media', 'En Progreso', 1009, 1037),

-- ==========================================
-- TAREAS ALEATORIAS PARA COMPLETAR EL TABLERO
-- ==========================================
(1039, 'Configuración de Servidores Linux', 'Instalación de Ubuntu Server, hardening y configuración de firewall UFW.', '2025-04-10', '2025-05-10', '2025-05-08', 80, 'Media', 'Finalizada', 1010, 1035),
(1040, 'Despliegue de Contenedores Docker', 'Empaquetado de aplicaciones y configuración de docker-compose para HA.', '2025-05-11', '2025-06-10', NULL, 80, 'Alta', 'En Progreso', 1010, 1015),
(1041, 'Levantamiento de Inventario Redes', 'Mapeo físico de puntos de red y etiquetado de cables en las 3 plantas del edificio.', '2024-02-15', '2024-03-15', '2024-03-12', 60, 'Baja', 'Finalizada', 1036, 1048),
(1044, 'Auditoría de Cajas Fuertes', 'Análisis de vulnerabilidades lógicas en el sistema de apertura electrónica de bóvedas.', '2025-06-15', '2025-07-15', NULL, 80, 'Alta', 'En Progreso', 1039, 1025),
(1046, 'Diseño de Base de Datos Odoo', 'Revisión y mapeo de los módulos nativos de Odoo v12 vs la nueva arquitectura en v16.', '2025-04-15', '2025-05-15', '2025-05-10', 60, 'Media', 'Finalizada', 1031, 1013),
(1048, 'Configuración de BGP y Routers', 'Establecimiento de protocolos de enrutamiento dinámico BGP en equipos Cisco Core.', '2024-11-20', '2024-12-20', '2024-12-18', 80, 'Alta', 'Finalizada', 1041, 1035),
(1054, 'Desarrollo Frontend del HelpDesk', 'Programación de la interfaz de tickets y bandeja de entrada para los operadores de soporte.', '2025-09-26', '2025-11-05', NULL, 120, 'Media', 'Pendiente', 1049, 1034),
(1060, 'Diseño de base de datos biométrica', 'Estructuración de tablas para almacenar hashes de huellas dactilares.', '2024-02-10', '2024-02-20', '2024-02-18', 40, 'Media', 'Finalizada', 1005, 1013),
(1062, 'Levantamiento de requerimientos B2B', 'Definición de reglas de negocio para distribuidores mayoristas.', '2025-09-15', '2025-09-30', '2025-09-28', 40, 'Media', 'Finalizada', 1006, 1023),
(1074, 'Wireframes de la nueva interfaz', 'Esqueletos estructurales (wireframes) de la nueva app de Mi Teleférico.', '2025-02-01', '2025-02-15', '2025-02-12', 40, 'Media', 'Finalizada', 1016, 1016);




-- ==========================================
-- FASE 11: DEPENDENCIAS DE TAREAS (DEPENDE) - MASIVO
-- ==========================================
INSERT INTO DEPENDE (id_tarea, id_tarea_previa) VALUES
-- P-1001: Facturación
(1002, 1001), 
(1003, 1002), 
(1004, 1002), 
(1004, 1003), 
(1005, 1003), 
(1005, 1004), 
(1006, 1005),
-- P-1002: Banca Joven
(1009, 1007), 
(1010, 1007), 
(1009, 1008), 
(1010, 1008), 
(1011, 1009), 
(1011, 1010),
-- P-1003: Portal Seguros
(1013, 1012), 
(1014, 1013), 
(1015, 1013),
-- P-1008: Migración AWS
(1017, 1016), 
(1018, 1017), 
(1019, 1018), 
(1019, 1017),
-- P-1015: App Delivery
(1021, 1020), 
(1022, 1020), 
(1023, 1021), 
(1023, 1022), 
(1024, 1023),
-- P-1022: Core Bancario
(1026, 1025), 
(1027, 1025), 
(1027, 1026), 
(1028, 1027), 
(1029, 1028),
-- P-1009: Data Lake
(1035, 1034), 
(1036, 1035), 
(1037, 1035), 
(1037, 1038), 
(1037, 1036),
-- Dependencias sueltas lógicas
(1040, 1039), 
(1062, 1060);


-- ==========================================
-- FASE 12.A: ASIGNACIÓN DE RECURSOS A PROYECTOS (UTILIZA) - MASIVO
-- Abarca la mayoría de los 50 proyectos para afectar el presupuesto global
-- ==========================================
INSERT INTO UTILIZA (id_proyecto, id_recurso, cantidad_usada, fecha_uso, observacion) VALUES
-- Desarrollo Web / APIs (Laptops, AWS EC2, Docker, Figma)
(1001, 1001, 4, '2025-01-15', 'Laptops Core i7 para Backend y QA'),
(1001, 1031, 2, '2025-01-20', 'Instancias AWS para entorno Staging'),
(1001, 1038, 4, '2025-01-15', 'Licencias Docker Pro'),
(1004, 1001, 2, '2025-08-01', 'Laptops para pasarela de pagos'),
(1006, 1031, 1, '2025-09-15', 'Instancia AWS B2B'),
(1013, 1038, 10, '2025-05-01', 'Suscripciones Docker para Microservicios'),
(1043, 1001, 3, '2024-05-01', 'Equipos para equipo Web Corporativo'),
(1043, 1035, 2, '2024-05-05', 'Figma para rediseño de portal'),

-- Desarrollo Mobile (MacBooks, iPhones, S23, Figma)
(1002, 1003, 2, '2025-03-01', 'MacBooks para compilar iOS'),
(1002, 1035, 2, '2025-03-05', 'Figma Diseño Banca'),
(1002, 1039, 3, '2025-03-10', 'Celulares Android Testing'),
(1002, 1040, 2, '2025-03-10', 'iPhones 14 Testing'),
(1015, 1003, 1, '2024-08-10', 'MacBook Delivery App'),
(1015, 1039, 5, '2024-08-15', 'Celulares con GPS para pruebas de campo'),
(1018, 1003, 2, '2024-11-01', 'Equipos Wallet Móvil'),
(1019, 1040, 2, '2025-07-15', 'Dispositivos Telemedicina QA'),

-- Infraestructura, Cloud y Redes (Servidores, Switches, Firewall)
(1008, 1007, 4, '2024-10-01', 'Servidores Dell R740 puente migración'),
(1008, 1032, 1, '2024-11-15', 'AWS RDS Postgres'),
(1008, 1033, 5, '2024-11-20', 'Buckets AWS S3 5TB'),
(1010, 1006, 2, '2025-04-10', 'Servidores HA Clúster'),
(1036, 1012, 3, '2024-02-15', 'Switches Cisco 48p LAN'),
(1036, 1014, 10, '2024-02-20', 'Access Points Ubiquiti'),
(1036, 1017, 5, '2024-02-15', 'Bobinas Cable UTP'),
(1038, 1015, 2, '2025-04-01', 'Fortinet FortiGate Perimetral'),
(1040, 1006, 5, '2025-08-01', 'Servidores HP Datacenter'),
(1040, 1021, 2, '2025-08-05', 'UPS Rack APC'),
(1042, 1011, 2, '2025-09-10', 'Switches PoE Telefonia VoIP'),

-- ERP, SAP y Datos (Licencias SQL, SAP, Odoo, Data Lakes)
(1009, 1033, 10, '2025-01-20', 'AWS S3 Data Lake (10TB)'),
(1009, 1001, 3, '2025-01-25', 'Laptops Ingenieros Datos'),
(1022, 1024, 1, '2024-01-10', 'Licencia SQL Server Core Bancario'),
(1026, 1027, 20, '2024-06-01', 'Licencias Odoo ERP Activos'),
(1029, 1023, 1, '2024-03-01', 'Windows Server para SAP'),
(1030, 1002, 5, '2025-01-10', 'Laptops ThinkPad para Retail ERP'),
(1031, 1027, 30, '2025-04-15', 'Licencias Odoo v16 Migración'),

-- Proyectos Varios (Ofimática, Seguridad, Testing)
(1005, 1042, 4, '2024-02-10', 'Cámaras Biométrico/Seguridad'),
(1024, 1026, 1, '2025-04-01', 'Antivirus Kaspersky Lote'),
(1039, 1001, 2, '2025-06-15', 'Laptops Pentesting Kali Linux'),
(1044, 1030, 50, '2025-02-10', 'Cuentas Workspace Intranet'),
(1049, 1005, 4, '2025-09-05', 'Monitores HelpDesk'),
(1050, 1046, 2, '2025-05-10', 'Escritorios Control Laboratorio');


-- ==========================================
-- FASE 12.B: REGISTRO DE AVANCE (HORAS DE TRABAJO) - MASIVO
-- Historial de horas reportadas para dar vida al Kanban y KPIs
-- ==========================================
INSERT INTO REGISTRO_AVANCE (fecha_reporte, horas_trabajadas, porcentaje_avance, detalle_trabajo, id_tarea, id_usuario) VALUES
-- Proyecto 1001 (Facturación)
('2025-01-20', 20, 50, 'Entrevistas con stakeholders (AS-IS).', 1001, 1023),
('2025-01-28', 20, 100, 'Documento funcional cerrado.', 1001, 1023),
('2025-01-25', 15, 50, 'Diseño ER 3FN completado.', 1002, 1013),
('2025-02-02', 15, 100, 'Base de datos montada en Docker.', 1002, 1013),
('2025-02-20', 40, 25, 'Estructura API REST Node.js.', 1003, 1011),
('2025-03-05', 40, 50, 'CRUD de facturas.', 1003, 1011),
('2025-03-15', 40, 75, 'Integración SOAP SIAT.', 1003, 1011),
('2025-03-28', 40, 100, 'Backend completado.', 1003, 1011),
('2025-03-01', 50, 30, 'Maquetación React iniciada.', 1004, 1012),
('2025-04-12', 110, 100, 'Frontend acoplado al Backend.', 1004, 1012),
('2025-05-08', 80, 100, 'Cypress y JMeter sin errores.', 1005, 1014),
('2025-06-08', 40, 100, 'Desplegado en EC2.', 1006, 1015),

-- Proyecto 1002 (Banca Móvil)
('2025-03-10', 30, 50, 'Wireframes Banca.', 1007, 1016),
('2025-03-18', 30, 100, 'Figma exportado a devs.', 1007, 1016),
('2025-04-15', 80, 40, 'Microservicios Spring Boot base.', 1008, 1017),
('2025-05-15', 60, 30, 'Vistas Android transacciones.', 1009, 1019),
('2025-04-12', 50, 100, 'Pipelines Bitbucket armados.', 1011, 1015),

-- Proyecto 1003 (Portal Seguros)
('2025-06-20', 30, 50, 'Mapeo siniestros automotores.', 1012, 1023),
('2025-06-28', 30, 100, 'Mapeo siniestros vida.', 1012, 1023),
('2025-07-14', 40, 100, 'Arquitectura Microservicios lista.', 1013, 1021),
('2025-08-15', 70, 45, 'Angular portal web a medias.', 1014, 1018),

-- Proyecto 1008 (Migración AWS)
('2024-10-12', 40, 100, 'Auditoría On-Premise lista.', 1016, 1035),
('2024-11-05', 40, 50, 'VPC y Subnets configuradas.', 1017, 1045),
('2024-11-10', 40, 100, 'VPN Site-to-Site operativa.', 1017, 1045),
('2024-12-15', 60, 50, 'AWS DMS trasladando tablas maestras.', 1018, 1027),
('2025-01-15', 60, 100, 'Datos 100% en la nube.', 1018, 1027),
('2025-02-25', 60, 100, 'Auto-scaling testeado.', 1019, 1042),

-- Proyecto 1015 (App Delivery)
('2024-08-22', 40, 100, 'Sprints Jira armados.', 1020, 1022),
('2024-09-10', 50, 100, 'Pantallas mapa y carrito.', 1021, 1046),
('2024-10-15', 70, 50, 'API Go + WebSockets.', 1022, 1047),
('2024-11-12', 70, 100, 'Backend ruteo optimizado.', 1022, 1047),
('2024-11-01', 100, 50, 'Android Chofer y Cliente base.', 1023, 1019),
('2024-12-05', 100, 100, 'SDK Maps acoplado. MVP listo.', 1023, 1019),
('2025-01-08', 60, 100, 'Pruebas GPS calle superadas.', 1024, 1029),

-- Proyecto 1022 (Core Bancario)
('2024-02-05', 80, 100, 'Fórmulas flat y francés levantadas.', 1025, 1023),
('2024-03-08', 80, 100, 'Seguridad y encriptación ok.', 1026, 1025),
('2024-05-15', 150, 50, 'Lógica financiera Java (Mitad).', 1027, 1017),
('2024-07-10', 150, 100, 'Cálculos de mora integrados.', 1027, 1017),
('2024-09-12', 120, 100, 'JUnit 90% cobertura.', 1028, 1014),
('2024-10-05', 60, 100, 'Manual oficial de cajas listo.', 1029, 1038),

-- Proyecto 1009 (Data Lake)
('2025-02-25', 100, 100, 'Modelo estrella definido.', 1034, 1026),
('2025-04-15', 80, 40, 'ETL 2 de 5 sistemas listos.', 1035, 1027),
('2025-05-10', 40, 50, 'Índices Oracle reconstruidos.', 1038, 1037),

-- Tareas Sueltas
('2025-05-08', 80, 100, 'Hardening Linux UFW.', 1039, 1035),
('2025-06-01', 40, 50, 'Dockerfiles redactados.', 1040, 1015),
('2024-03-12', 60, 100, 'Etiquetado red 3 pisos.', 1041, 1048),
('2025-05-10', 60, 100, 'Mapeo módulos Odoo.', 1046, 1013),
('2024-12-18', 80, 100, 'BGP Cisco Core convergido.', 1048, 1035),
('2024-02-18', 40, 100, 'Tablas hashes huellas listas.', 1060, 1013),
('2025-09-28', 40, 100, 'Lógica B2B documentada.', 1062, 1023),
('2025-02-12', 40, 100, 'Wireframes Teleférico aprobados.', 1074, 1016);





-- ==========================================
-- FASE 14: HISTORIAL DE ESTADOS (AUDITORÍA MASIVA CON IDs)
-- Cubre los movimientos de la mayoría de los 50 proyectos y tareas
-- ==========================================
INSERT INTO HISTORIAL_ESTADO (id_historial, tabla_referencia, id_referencia, estado_anterior, estado_nuevo, fecha_cambio, id_usuario) VALUES

-- --------------------------------------------------------
-- 1. MOVIMIENTOS DE PROYECTOS (Gerentes iniciando y cerrando)
-- --------------------------------------------------------
-- Gerente Andrea (1004)
(1001, 'PROYECTO', 1001, 'Pendiente', 'En Progreso', '2025-01-15 08:00:00', 1004),
(1002, 'PROYECTO', 1001, 'En Progreso', 'Finalizada', '2025-06-10 18:30:00', 1004),
(1003, 'PROYECTO', 1002, 'Pendiente', 'En Progreso', '2025-03-01 09:15:00', 1004),
(1004, 'PROYECTO', 1003, 'Pendiente', 'En Progreso', '2025-06-10 08:45:00', 1004),
(1005, 'PROYECTO', 1005, 'Pendiente', 'En Progreso', '2024-02-10 10:00:00', 1004),
(1006, 'PROYECTO', 1005, 'En Progreso', 'Finalizada', '2024-05-15 16:20:00', 1004),
(1007, 'PROYECTO', 1007, 'Pendiente', 'En Progreso', '2025-02-20 11:30:00', 1004),

-- Gerente Diego (1005)
(1008, 'PROYECTO', 1008, 'Pendiente', 'En Progreso', '2024-10-01 08:00:00', 1005),
(1009, 'PROYECTO', 1008, 'En Progreso', 'Finalizada', '2025-03-05 17:00:00', 1005),
(1010, 'PROYECTO', 1009, 'Pendiente', 'En Progreso', '2025-01-20 09:00:00', 1005),
(1011, 'PROYECTO', 1010, 'Pendiente', 'En Progreso', '2025-04-10 08:30:00', 1005),
(1012, 'PROYECTO', 1012, 'Pendiente', 'En Progreso', '2024-05-15 09:45:00', 1005),
(1013, 'PROYECTO', 1012, 'En Progreso', 'Finalizada', '2024-12-01 15:10:00', 1005),
(1014, 'PROYECTO', 1013, 'Pendiente', 'En Progreso', '2025-05-01 10:00:00', 1005),

-- Gerente Camila (1006)
(1015, 'PROYECTO', 1015, 'Pendiente', 'En Progreso', '2024-08-10 08:15:00', 1006),
(1016, 'PROYECTO', 1015, 'En Progreso', 'Finalizada', '2025-01-20 16:45:00', 1006),
(1017, 'PROYECTO', 1016, 'Pendiente', 'En Progreso', '2025-02-01 09:00:00', 1006),
(1018, 'PROYECTO', 1017, 'Pendiente', 'En Progreso', '2025-05-15 08:30:00', 1006),
(1019, 'PROYECTO', 1018, 'Pendiente', 'En Progreso', '2024-11-01 10:20:00', 1006),
(1020, 'PROYECTO', 1018, 'En Progreso', 'Finalizada', '2025-05-05 14:00:00', 1006),
(1021, 'PROYECTO', 1020, 'Pendiente', 'En Progreso', '2025-03-10 09:10:00', 1006),

-- Gerente Javier (1007)
(1022, 'PROYECTO', 1022, 'Pendiente', 'En Progreso', '2024-01-10 08:30:00', 1007),
(1023, 'PROYECTO', 1022, 'En Progreso', 'Finalizada', '2024-11-05 11:20:00', 1007),
(1024, 'PROYECTO', 1023, 'Pendiente', 'En Progreso', '2025-02-15 09:00:00', 1007),
(1025, 'PROYECTO', 1024, 'Pendiente', 'En Progreso', '2025-04-01 08:45:00', 1007),
(1026, 'PROYECTO', 1026, 'Pendiente', 'En Progreso', '2024-06-01 10:00:00', 1007),
(1027, 'PROYECTO', 1026, 'En Progreso', 'Finalizada', '2024-10-02 16:30:00', 1007),
(1028, 'PROYECTO', 1027, 'Pendiente', 'En Progreso', '2025-05-20 09:15:00', 1007),

-- Gerente Lucía (1008)
(1029, 'PROYECTO', 1029, 'Pendiente', 'En Progreso', '2024-03-01 08:00:00', 1008),
(1030, 'PROYECTO', 1029, 'En Progreso', 'Finalizada', '2025-01-15 15:45:00', 1008),
(1031, 'PROYECTO', 1030, 'Pendiente', 'En Progreso', '2025-01-10 09:30:00', 1008),
(1032, 'PROYECTO', 1031, 'Pendiente', 'En Progreso', '2025-04-15 08:20:00', 1008),
(1033, 'PROYECTO', 1033, 'Pendiente', 'En Progreso', '2024-09-10 10:00:00', 1008),
(1034, 'PROYECTO', 1033, 'En Progreso', 'Finalizada', '2024-12-20 17:10:00', 1008),
(1035, 'PROYECTO', 1034, 'Pendiente', 'En Progreso', '2025-03-20 09:05:00', 1008),

-- Gerente Rodrigo (1009)
(1036, 'PROYECTO', 1036, 'Pendiente', 'En Progreso', '2024-02-15 08:00:00', 1009),
(1037, 'PROYECTO', 1036, 'En Progreso', 'Finalizada', '2024-06-10 16:00:00', 1009),
(1038, 'PROYECTO', 1037, 'Pendiente', 'En Progreso', '2025-01-05 08:30:00', 1009),
(1039, 'PROYECTO', 1037, 'En Progreso', 'Finalizada', '2025-05-12 15:20:00', 1009),
(1040, 'PROYECTO', 1038, 'Pendiente', 'En Progreso', '2025-04-01 09:15:00', 1009),
(1041, 'PROYECTO', 1039, 'Pendiente', 'En Progreso', '2025-06-15 10:00:00', 1009),
(1042, 'PROYECTO', 1041, 'Pendiente', 'En Progreso', '2024-11-20 08:45:00', 1009),
(1043, 'PROYECTO', 1041, 'En Progreso', 'Finalizada', '2025-03-25 17:30:00', 1009),

-- Gerente Paola (1010)
(1044, 'PROYECTO', 1043, 'Pendiente', 'En Progreso', '2024-05-01 08:00:00', 1010),
(1045, 'PROYECTO', 1043, 'En Progreso', 'Finalizada', '2024-07-25 16:15:00', 1010),
(1046, 'PROYECTO', 1044, 'Pendiente', 'En Progreso', '2025-02-10 09:00:00', 1010),
(1047, 'PROYECTO', 1045, 'Pendiente', 'En Progreso', '2025-03-15 08:30:00', 1010),
(1048, 'PROYECTO', 1047, 'Pendiente', 'En Progreso', '2024-08-15 10:20:00', 1010),
(1049, 'PROYECTO', 1047, 'En Progreso', 'Finalizada', '2024-12-28 15:45:00', 1010),
(1050, 'PROYECTO', 1048, 'Pendiente', 'En Progreso', '2025-04-20 09:10:00', 1010),
(1051, 'PROYECTO', 1050, 'Pendiente', 'En Progreso', '2025-05-10 08:50:00', 1010),

-- Movimientos Especiales (Proyectos que se pausaron y luego se retomaron)
(1052, 'PROYECTO', 1003, 'En Progreso', 'En Pausa', '2025-07-01 10:00:00', 1004),
(1053, 'PROYECTO', 1003, 'En Pausa', 'En Progreso', '2025-07-15 08:00:00', 1004),
(1054, 'PROYECTO', 1010, 'En Progreso', 'En Pausa', '2025-05-20 14:30:00', 1005),
(1055, 'PROYECTO', 1010, 'En Pausa', 'En Progreso', '2025-06-01 09:00:00', 1005),
(1056, 'PROYECTO', 1031, 'En Progreso', 'En Pausa', '2025-05-10 11:00:00', 1008),
(1057, 'PROYECTO', 1031, 'En Pausa', 'En Progreso', '2025-05-25 08:30:00', 1008),

-- --------------------------------------------------------
-- 2. MOVIMIENTOS DE TAREAS (Desarrolladores actualizando el Kanban)
-- --------------------------------------------------------
-- Tareas del Proyecto 1001 (Facturación)
(1058, 'TAREA', 1001, 'Pendiente', 'En Progreso', '2025-01-15 09:30:00', 1023),
(1059, 'TAREA', 1001, 'En Progreso', 'Finalizada', '2025-01-28 16:45:00', 1023),
(1060, 'TAREA', 1002, 'Pendiente', 'En Progreso', '2025-01-20 10:00:00', 1013),
(1061, 'TAREA', 1002, 'En Progreso', 'Finalizada', '2025-02-02 11:20:00', 1013),
(1062, 'TAREA', 1003, 'Pendiente', 'En Progreso', '2025-02-01 08:30:00', 1011),
(1063, 'TAREA', 1003, 'En Progreso', 'Finalizada', '2025-03-28 18:00:00', 1011),
(1064, 'TAREA', 1004, 'Pendiente', 'En Progreso', '2025-02-15 09:15:00', 1012),
(1065, 'TAREA', 1004, 'En Progreso', 'Finalizada', '2025-04-12 17:30:00', 1012),
(1066, 'TAREA', 1005, 'Pendiente', 'En Progreso', '2025-04-10 08:00:00', 1014),
(1067, 'TAREA', 1005, 'En Progreso', 'Finalizada', '2025-05-08 15:45:00', 1014),
(1068, 'TAREA', 1006, 'Pendiente', 'En Progreso', '2025-05-15 10:00:00', 1015),
(1069, 'TAREA', 1006, 'En Progreso', 'Finalizada', '2025-06-08 14:20:00', 1015),

-- Tareas Proyecto 1002 (Banca Móvil)
(1070, 'TAREA', 1007, 'Pendiente', 'En Progreso', '2025-03-01 08:30:00', 1016),
(1071, 'TAREA', 1007, 'En Progreso', 'Finalizada', '2025-03-18 16:00:00', 1016),
(1072, 'TAREA', 1008, 'Pendiente', 'En Progreso', '2025-03-21 09:00:00', 1017),
(1073, 'TAREA', 1009, 'Pendiente', 'En Progreso', '2025-04-01 10:15:00', 1019),
(1074, 'TAREA', 1011, 'Pendiente', 'En Progreso', '2025-03-15 08:00:00', 1015),
(1075, 'TAREA', 1011, 'En Progreso', 'Finalizada', '2025-04-12 15:30:00', 1015),

-- Tareas Proyecto 1008 (Migración AWS)
(1076, 'TAREA', 1016, 'Pendiente', 'En Progreso', '2024-10-01 08:30:00', 1035),
(1077, 'TAREA', 1016, 'En Progreso', 'Finalizada', '2024-10-12 16:10:00', 1035),
(1078, 'TAREA', 1017, 'Pendiente', 'En Progreso', '2024-10-16 09:00:00', 1045),
(1079, 'TAREA', 1017, 'En Progreso', 'Finalizada', '2024-11-10 14:45:00', 1045),
(1080, 'TAREA', 1018, 'Pendiente', 'En Progreso', '2024-11-20 08:15:00', 1027),
(1081, 'TAREA', 1018, 'En Progreso', 'Finalizada', '2025-01-15 17:00:00', 1027),
(1082, 'TAREA', 1019, 'Pendiente', 'En Progreso', '2025-01-21 09:30:00', 1042),
(1083, 'TAREA', 1019, 'En Progreso', 'Finalizada', '2025-02-25 15:20:00', 1042),

-- Tareas Proyecto 1015 (App Delivery)
(1084, 'TAREA', 1020, 'Pendiente', 'En Progreso', '2024-08-10 08:00:00', 1022),
(1085, 'TAREA', 1020, 'En Progreso', 'Finalizada', '2024-08-22 16:30:00', 1022),
(1086, 'TAREA', 1021, 'Pendiente', 'En Progreso', '2024-08-26 09:15:00', 1046),
(1087, 'TAREA', 1021, 'En Progreso', 'Finalizada', '2024-09-10 15:00:00', 1046),
(1088, 'TAREA', 1022, 'Pendiente', 'En Progreso', '2024-09-16 08:45:00', 1047),
(1089, 'TAREA', 1022, 'En Progreso', 'Finalizada', '2024-11-12 17:10:00', 1047),
(1090, 'TAREA', 1023, 'Pendiente', 'En Progreso', '2024-10-01 10:00:00', 1019),
(1091, 'TAREA', 1023, 'En Progreso', 'Finalizada', '2024-12-05 14:45:00', 1019),
(1092, 'TAREA', 1024, 'Pendiente', 'En Progreso', '2024-12-11 08:30:00', 1029),
(1093, 'TAREA', 1024, 'En Progreso', 'Finalizada', '2025-01-08 16:20:00', 1029),

-- Tareas Sueltas
(1094, 'TAREA', 1039, 'Pendiente', 'En Progreso', '2025-04-10 09:00:00', 1035),
(1095, 'TAREA', 1039, 'En Progreso', 'Finalizada', '2025-05-08 17:00:00', 1035),
(1096, 'TAREA', 1041, 'Pendiente', 'En Progreso', '2024-02-15 08:30:00', 1048),
(1097, 'TAREA', 1041, 'En Progreso', 'Finalizada', '2024-03-12 16:20:00', 1048),
(1098, 'TAREA', 1046, 'Pendiente', 'En Progreso', '2025-04-15 09:15:00', 1013),
(1099, 'TAREA', 1046, 'En Progreso', 'Finalizada', '2025-05-10 15:00:00', 1013);





-- ==========================================
-- FASE 15: COMUNICACIÓN Y COLABORACIÓN (COMENTARIOS Y MENSAJES)
-- ==========================================

-- --------------------------------------------------------
-- 1. COMENTARIOS EN TAREAS (Comunicación técnica en el Kanban)
-- --------------------------------------------------------
INSERT INTO COMENTARIO (id_comentario, contenido, fecha_comentario, id_tarea, id_usuario) VALUES
-- Discusión en Tarea 1003 (Backend Node.js SIAT)
(1001, 'He subido el PR con la estructura base de Express y JWT. ¿Alguien puede revisarlo?', '2025-02-16 10:00:00', 1003, 1011),
(1002, 'Código revisado. Todo excelente, pero recuerda agregar los logs de Winston para auditoría.', '2025-02-16 14:30:00', 1003, 1013),
(1003, 'Añadidos los logs en el último commit. Procedo a hacer merge a la rama develop.', '2025-02-17 09:15:00', 1003, 1011),

-- Discusión en Tarea 1005 (Pruebas de Estrés SIAT)
(1004, 'Detecté un cuello de botella en la consulta de facturas cuando simulamos 500 usuarios. El CPU de AWS se dispara al 90%.', '2025-04-15 11:20:00', 1005, 1014),
(1005, 'Revisaré los índices de la base de datos hoy mismo. Creo que falta un índice compuesto en la tabla principal.', '2025-04-15 11:45:00', 1005, 1013),
(1006, 'Índices aplicados. Vuelve a correr JMeter por favor.', '2025-04-16 08:30:00', 1005, 1013),
(1007, 'Confirmado. El CPU ahora se mantiene estable al 40% con 1000 usuarios concurrentes. ¡Buen trabajo!', '2025-04-16 15:00:00', 1005, 1014),

-- Discusión en Tarea 1022 (API Go Delivery)
(1008, 'Los WebSockets se están desconectando cuando la app pasa a segundo plano en Android.', '2024-10-20 09:15:00', 1022, 1019),
(1009, 'Implementé un ping/pong ("Heartbeat") cada 15 segundos desde el servidor. Prueba con la última imagen de Docker.', '2024-10-21 10:00:00', 1022, 1047),
(1010, 'Funciona perfecto ahora. La conexión persiste incluso con la pantalla apagada.', '2024-10-21 16:30:00', 1022, 1019),

-- Discusión en Tarea 1035 (ETL Data Lake)
(1011, 'El volcado de datos históricos desde el Oracle antiguo tardó 8 horas anoche. Necesitamos optimizar esto.', '2025-04-05 08:00:00', 1035, 1027),
(1012, 'Hagamos cargas incrementales basadas en la columna de última_modificación en vez de un full dump.', '2025-04-05 09:30:00', 1035, 1037),

-- Discusión en Tarea 1026 (Diseño Seguridad Core Bancario)
(1013, 'El algoritmo de encriptación para las contraseñas debe ser bcrypt con un salt de 12 rondas mínimo.', '2024-02-15 10:00:00', 1026, 1025),
(1014, 'Entendido. Ya configuré Spring Security para usar bcrypt.', '2024-02-16 11:15:00', 1026, 1017);



-- --------------------------------------------------------
-- 2. CHAT INTERNO Y MENSAJERÍA DIRECTA (MENSAJE)
-- --------------------------------------------------------
INSERT INTO MENSAJE (id_mensaje, contenido, fecha_envio, leido, id_remitente, id_destinatario, id_proyecto) VALUES
-- Hilo de chat: Andrea (PM) y Miguel (Líder Backend) - Proyecto 1001
(1001, 'Hola Miguel, ¿cómo vamos con la integración SOAP de Impuestos? El cliente está pidiendo un demo para el viernes.', '2025-03-20 09:00:00', TRUE, 1004, 1011, 1001),
(1002, 'Buen día Andrea. Ya estamos recibiendo el token correctamente. Hoy termino de parsear el XML de respuesta y mañana lo tienes listo para el demo.', '2025-03-20 09:15:00', TRUE, 1011, 1004, 1001),
(1003, 'Excelente. Avísame apenas lo subas a pre-producción para que QA le dé una revisión rápida.', '2025-03-20 09:20:00', TRUE, 1004, 1011, 1001),

-- Hilo de chat: Diego (PM) y Julio (DevOps) - Proyecto 1008
(1004, 'Julio, el equipo de QA dice que el entorno de Staging está caído. ¿Hubo algún problema con el despliegue?', '2024-11-05 14:00:00', TRUE, 1005, 1015, 1008),
(1005, 'Sí, hubo un problema con los certificados SSL de Let''s Encrypt, expiraron. Ya los estoy renovando, en 10 minutos vuelve arriba.', '2024-11-05 14:05:00', TRUE, 1015, 1005, 1008),
(1006, 'Confirmado, el entorno vuelve a estar online.', '2024-11-05 14:15:00', TRUE, 1015, 1005, 1008),

-- Hilo de chat: Camila (PM) y Héctor (Android) - Proyecto 1015
(1007, 'Héctor, necesito que des prioridad a la vista del mapa. El algoritmo de ruteo ya está en la API.', '2024-10-15 10:30:00', TRUE, 1006, 1019, 1015),
(1008, 'Recibido Camila. Empiezo a integrar el SDK de Google Maps ahora mismo.', '2024-10-15 10:45:00', TRUE, 1019, 1006, 1015),

-- Mensajes de bienvenida institucionales y notificaciones
(1009, '¡Bienvenido al equipo de Infraestructura Cloud! Por favor revisa la documentación en la intranet antes de empezar.', '2024-10-01 08:30:00', TRUE, 1001, 1045, 1008),
(1010, 'Hola equipo. Recuerden registrar sus horas en el sistema de avance antes de terminar la jornada. ¡Gracias!', '2025-01-30 17:00:00', FALSE, 1004, 1012, 1001),

-- Hilo Técnico: Frontend (Sofía) y Backend (Miguel) - Proyecto 1001
(1011, 'Miguel, el endpoint de /api/facturas me está devolviendo un error 500 cuando envío el campo de "descuento" nulo.', '2025-03-10 11:00:00', TRUE, 1012, 1011, 1001),
(1012, 'Déjame revisar. Seguro me faltó validar eso en el DTO. Dame 5 minutos.', '2025-03-10 11:05:00', TRUE, 1011, 1012, 1001),
(1013, 'Listo, ya le hice un parche rápido y está en la rama dev. Ahora acepta nulos y los convierte a 0.00 por defecto.', '2025-03-10 11:15:00', FALSE, 1011, 1012, 1001);




-- ==========================================
-- SINCRONIZACIÓN DE SECUENCIAS (IDENTITY)
-- ==========================================

-- USUARIO
SELECT setval(
    pg_get_serial_sequence('usuario', 'id_usuario'),
    COALESCE((SELECT MAX(id_usuario) FROM usuario), 1),
    true
);

-- CLIENTE
SELECT setval(
    pg_get_serial_sequence('cliente', 'id_cliente'),
    COALESCE((SELECT MAX(id_cliente) FROM cliente), 1),
    true
);

-- RECURSO_MATERIAL
SELECT setval(
    pg_get_serial_sequence('recurso_material', 'id_recurso'),
    COALESCE((SELECT MAX(id_recurso) FROM recurso_material), 1),
    true
);

-- PROYECTO
SELECT setval(
    pg_get_serial_sequence('proyecto', 'id_proyecto'),
    COALESCE((SELECT MAX(id_proyecto) FROM proyecto), 1),
    true
);

-- TAREA
SELECT setval(
    pg_get_serial_sequence('tarea', 'id_tarea'),
    COALESCE((SELECT MAX(id_tarea) FROM tarea), 1),
    true
);

-- REGISTRO_AVANCE
SELECT setval(
    pg_get_serial_sequence('registro_avance', 'id_registro'),
    COALESCE((SELECT MAX(id_registro) FROM registro_avance), 1),
    true
);

-- COMENTARIO
SELECT setval(
    pg_get_serial_sequence('comentario', 'id_comentario'),
    COALESCE((SELECT MAX(id_comentario) FROM comentario), 1),
    true
);

-- MENSAJE
SELECT setval(
    pg_get_serial_sequence('mensaje', 'id_mensaje'),
    COALESCE((SELECT MAX(id_mensaje) FROM mensaje), 1),
    true
);

-- HISTORIAL_ESTADO
SELECT setval(
    pg_get_serial_sequence('historial_estado', 'id_historial'),
    COALESCE((SELECT MAX(id_historial) FROM historial_estado), 1),
    true
);
